services:
    ilioscli.command.invalidate_user_tokens:
        class: Ilios\CliBundle\Command\InvalidateUserTokenCommand
        arguments: ["@ilioscore.user.manager", "@ilioscore.authentication.manager"]
        tags:
            -  { name: console.command }
    ilioscli.command.create_user_token:
        class: Ilios\CliBundle\Command\CreateUserTokenCommand
        arguments: ["@ilioscore.user.manager", "@ilios_authentication.jwt.manager"]
        tags:
            -  { name: console.command }
    ilioscli.command.sync_user:
        class: Ilios\CliBundle\Command\SyncUserCommand
        arguments: ["@ilioscore.user.manager", "@ilioscore.directory"]
        tags:
            -  { name: console.command }
    ilioscli.command.find_directory_user:
        class: Ilios\CliBundle\Command\FindUserCommand
        arguments: ["@ilioscore.directory"]
        tags:
            -  { name: console.command }
    ilioscli.command.add_directory_user:
        class: Ilios\CliBundle\Command\AddUserCommand
        arguments: ["@ilioscore.user.manager", "@ilioscore.authentication.manager", "@ilioscore.school.manager", "@ilioscore.directory", "@ilios_authentication.authenticator"]
        tags:
            -  { name: console.command }
    ilioscli.command.sync_former_students:
        class: Ilios\CliBundle\Command\SyncFormerStudentsCommand
        arguments: ["@ilioscore.user.manager", "@ilioscore.userrole.manager", "@ilioscore.directory"]
        tags:
            -  { name: console.command }
