framework:
  cache:
    # Put the unique name of your app here: the prefix seed
    # is used to compute stable namespaces for cache keys.
    prefix_seed: ilios/api

    pools:
      doctrine.annotation_cache_pool:
        adapter: cache.system