exercise_html_purifier:
  # full configuration reference: http://htmlpurifier.org/live/configdoc/plain.html
  html_profiles:
    default:
      config:
        HTML.Allowed: 'a[href|target],br,div,dd,dl,dt,em,li,ol,p,strong,sub,sup,ul'
        # the charset used by the original contents
        Core.Encoding: 'UTF-8'
        Attr.AllowedFrameTargets:
          - '_blank'