framework:
    messenger:
        failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
             async:
               dsn: "doctrine://default"
               options:
                 queue_name: async
                 auto_setup: false
             failed:
               dsn: "doctrine://default"
               options:
                 queue_name: failed
                 auto_setup: false

        routing:
            # Route your messages to the transports
             'App\Message\CourseIndexRequest': async
             'App\Message\UserIndexRequest': async
             'App\Message\MeshDescriptorIndexRequest': async
