liip_monitor:
  enable_controller: true
  default_group: default
  checks:
    groups:
      default:
        php_extensions: [apcu, mbstring, ldap, xml, dom, mysqlnd, pdo, zip, json, zlib, ctype, iconv]
        php_version:
            "8.2": ">="
        readable_directory: ["%kernel.cache_dir%"]
        writable_directory: ["%kernel.cache_dir%"]
      production:
        doctrine_dbal: [default]
        doctrine_migrations:
            migrations_with_doctrine_bundle:
              connection: default
        apc_memory:
          warning:              70
          critical:             90
        apc_fragmentation:
          warning:              70
          critical:             90
