nelmio_api_doc:
    documentation:
        info:
            title: Ilios API Documentation
            version: v3.6
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
        security:
            - Bearer: []
    areas: # to filter documented areas
        path_patterns:
            - ^/api/{version}/.*$
