security:
  access_decision_manager:
    allow_if_all_abstain: false
    strategy: unanimous
  firewalls:
    api_docs:
      pattern:   ^/api/doc
      anonymous: ~
    anonymous_auth:
      pattern:    ^/(auth|application)/(login|config|logout)
      anonymous: ~
    authenticated_auth:
      pattern:    ^/auth
      stateless: true
      guard:
        authenticators:
          - App\Security\JsonWebTokenAuthenticator
      provider: session_user
    authenticated_application:
      pattern:    ^/application
      stateless: true
      guard:
        authenticators:
          - App\Security\JsonWebTokenAuthenticator
      provider: session_user
    authenticated_search:
      pattern:    ^/experimental_search
      stateless: true
      guard:
        authenticators:
          - App\Security\JsonWebTokenAuthenticator
      provider: session_user
    upload:
      pattern:    ^/upload
      stateless: true
      guard:
        authenticators:
          - App\Security\JsonWebTokenAuthenticator
      provider: session_user
    errors:
      pattern:    ^/errors
      stateless: true
      guard:
        authenticators:
          - App\Security\JsonWebTokenAuthenticator
      provider: session_user
    default:
      pattern:    ^/api
      stateless: true
      guard:
        authenticators:
          - App\Security\JsonWebTokenAuthenticator
      provider: session_user
  providers:
    session_user:
      id: App\Service\SessionUserProvider
  encoders:
    App\Classes\SessionUserInterface:
      algorithm: bcrypt
    ilios_legacy_encoder:
      id: App\Form\Encoder
