security:
  enable_authenticator_manager: true
  access_control:
    - { path: '^/api/doc', roles: PUBLIC_ACCESS }
    - { path: '^/api$', roles: PUBLIC_ACCESS }
    - { path: '^/lm/[a-zA-Z0-9]{64}$', roles: PUBLIC_ACCESS }
    - { path: '^/ci-report-dl/[a-zA-Z0-9]{64}$', roles: PUBLIC_ACCESS }
    - { path: '^/application/config', roles: PUBLIC_ACCESS }
    - { path: '^/auth/(login|logout)', roles: PUBLIC_ACCESS }
    - { path: '^/', roles: IS_AUTHENTICATED_FULLY }
  access_decision_manager:
    allow_if_all_abstain: false
    strategy: unanimous
  password_hashers:
    App\Classes\SessionUserInterface:
      algorithm: auto
      migrate_from:
        - bcrypt
  providers:
    session_user:
      id: App\Service\SessionUserProvider
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      stateless: true
      custom_authenticators:
        - App\Security\JsonWebTokenAuthenticator
      provider: session_user

