when@prod:
    sentry:
        dsn: "https://c70286fb157048be9ebc6e918e8c2b79@o200403.ingest.sentry.io/1323198"
        options:
            before_send: 'App\Service\SentryBeforeSend'
            send_default_pii: true
#    If you are using Monolog, you also need these additional configuration and services to log the errors correctly:
#    https://docs.sentry.io/platforms/php/guides/symfony/#monolog-integration
#    register_error_listener: false
#        monolog:
#            handlers:
#                sentry:
#                    type: service
#                    id: Sentry\Monolog\Handler
#            services:
#                Sentry\Monolog\Handler:
#                    arguments:
#                        $hub: '@Sentry\State\HubInterface'
#                        $level: !php/const Monolog\Logger::ERROR
#                        $bubble: false
