language: php

php:
  - "5.4"
  - "5.3"

install:
  - pear channel-discover pear.phpunit.de
  - pear install phpunit/DbUnit
  - pear channel-discover pear.phing.info
  - pear install phing/phing
  - phpenv rehash

before_script:
# Provision web server for Behat tests
  - "sudo apt-get install -y --force-yes mysql-server apache2 libapache2-mod-php5 php5-mysql php5-ldap sendmail expect > /dev/null"
  - "sudo /usr/sbin/a2enmod rewrite && sudo /usr/sbin/a2enmod headers && sudo /usr/sbin/a2enmod ssl"
  - "sudo /bin/ln -s /etc/apache2/sites-available/default-ssl /etc/apache2/sites-enabled/000-default-ssl"
  - "(cd /etc/apache2/sites-enabled && sudo /usr/bin/find . -! -type d -exec /bin/sed -i '/<Directory \\/var\\/www\\/>/,/<\\/Directory>/ { s,AllowOverride None,AllowOverride All,}' {} \\;)"
  - "sudo /usr/bin/find /etc/apache2/sites-enabled -! -type d -exec /bin/sed -i \"s,/var/www,${PWD}/web,g\" {} \\;"
  - sudo sed -i -e "/DocumentRoot/i\ServerName precise64" /etc/apache2/sites-available/default
  - echo "127.0.0.1 precise64" | sudo tee -a /etc/hosts
  - "sudo /etc/init.d/apache2 restart"

# Get Selenium standalone server and run it for Behat tests
  - "wget http://selenium.googlecode.com/files/selenium-server-standalone-2.39.0.jar"
  - "java -jar selenium-server-standalone-2.39.0.jar -role hub > /dev/null &"

# Install the Ilios PHP app locally for PHPUnit testing
  - phing -q -propertyfile build.properties.sample -Dskip-prompt=true -Dskip-db-backup=true -Ddb.username=root -Ddb.password= -Ddb.group=ilios_test -Dencryption_key=lorem_ipsum -Ddeploydir=${PWD}/web -Dbackupdir=${PWD}/backup -Dwebuser=${USER} -Dwebgroup="`id -g -n`"

# Start Phantom for headless Behat tests
  - "phantomjs --webdriver=8080 --webdriver-selenium-grid-hub=http://127.0.0.1:4444 --ignore-ssl-errors=true > /dev/null &"

# Install Behat tests
  - composer install -d tests/behat

script:
# Run PHPUnit tests
  - "phpunit -c ${PWD}/tests/phpunit/default.phpunit.xml --include-path ${PWD}/tests/phpunit --exclude-group ldap tests/phpunit/Ilios"
# Because the PHPUnit tests unfortunately pollute the database, do a clean reinstall before running Behat tests.
  - phing db-install -q -propertyfile build.properties.sample -Dskip-prompt=true -Dskip-db-backup=true -Ddb.username=root -Ddb.password= -Ddb.group=ilios_test -Dencryption_key=lorem_ipsum -Ddeploydir=${PWD}/web -Dbackupdir=${PWD}/backup -Dwebuser=${USER} -Dwebgroup="`id -g -n`"

# Run Behat tests
  - "(cd tests/behat && bin/behat -p travis)"

# env variables for Sauce credentials, see https://saucelabs.com/opensource/travis
env:
  global:
    - secure: alzy+bShe22tWtRKIoF3qiWTFz2e5SawqIy1MNo5uPyft4KPWzBuH6ujg/CFLEB6BIwO9CFPPNUrnV0MwCXZ51+oTHyEDWpQdX9gvzL8b1tG0yt6Lx3qeQnLmrR28qOaDqe7GD/yi8Pula3sob4MiucOCYOCRhKvPOSNYWefKRw=
    - secure: iSmY1HlcUZZwjmzKz4pb4pNqgM1vlY6YSZ7ZL77Sr19ddGFT3SFoBRESBMjmdI51VbkmaAZSbkTIuLyTUwvvlTqUZMg5cSiGtZvfV0BPUAAW1WN9aryI+6sa1NmMfgp6sqoS6zf2/dSwT81SjREvsiTCgTznDgEoVKjot1gq2i4=


