language: php
services: mysql
sudo: false

php:
  - "5.4"

install:
  - composer install  --no-interaction -d ${TRAVIS_BUILD_DIR}
  - cp ${TRAVIS_BUILD_DIR}/app/config/parameters.yml.travis ${TRAVIS_BUILD_DIR}/app/config/parameters.yml

before_script:
#initialize symfony test db
  - bin/console doctrine:database:create --env=test
  - bin/console doctrine:schema:create --env=test

script:
  - bin/phpcs --standard=app/phpcs.xml src
  - bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
  - php bin/coveralls #send test coverage informatio to coveralls

#encrypted the IRC room chat.freenode.net##ilios so that it doesn't run on pull requests
notifications:
  irc:
    secure: "LN3o6qWNjtQepmrtRTEpFUoa9jFar6l5CDw1pwYzLSJOWc+q59tzbXyoKUlGat9/z+s79euUz2Pcg8XF0fotBwNKArPUOHH2Ti74JbZXNkEstPxgNe5CVqRkwvjlDvMeCJPOqxoc1xD6Ss/XNc5Tu414aIym2Zd4mJ0utmyBOUA="
