language: php

services: mysql

php:
  - "5.4"

env:
  global:
    - SAUCE_USERNAME="ilios"
    - SAUCE_ACCESS_KEY="e7c24f1d-ec10-435d-9cec-d1c38bafa268"

addons:
  hosts:
    - precise64

install:
  - composer install  --no-interaction -d ${TRAVIS_BUILD_DIR}
  - cp ${TRAVIS_BUILD_DIR}/app/config/parameters.yml.travis ${TRAVIS_BUILD_DIR}/app/config/parameters.yml

before_script:
#initialize symfony test db
  - bin/console doctrine:database:create --env=test
  - bin/console doctrine:schema:create --env=test

script:
  - bin/phpcs --standard=app/phpcs.xml src
  - bin/phpunit
