language: php

services: mysql

matrix:
  fast_finish: true

php:
  - "5.4"

env:
  global:
    #set these here becuase they get pullout by the behat SaucelabsFactory driver
    - SAUCE_USERNAME="ilios"
    - SAUCE_ACCESS_KEY="e7c24f1d-ec10-435d-9cec-d1c38bafa268"
    - ILIOS_THREE=false
  matrix:
    - ILIOS_THREE=true

addons:
  hosts:
    - precise64
  # sauce_connect addon is current disabled for pull requests so we can't use this
  # very simple way, instead we need to download sauce_connect manually
  #sauce_connect: true

before_install:
  - sudo apt-get update -qq

install:
  # Install composer packages in the app root. This will set up phing.
  - composer install  --no-interaction -d ${TRAVIS_BUILD_DIR}

# Install the Ilios PHP database locally for testing
  - cd ${TRAVIS_BUILD_DIR}; pwd; ${TRAVIS_BUILD_DIR}/bin/phing -q -propertyfile ${TRAVIS_BUILD_DIR}/build.properties.sample -Dskip-prompt=true -Dskip-db-backup=true -Ddb.username=root -Ddb.password= -Ddb.group=ilios_test -Dencryption_key=lorem_ipsum -Ddeploydir=${TRAVIS_BUILD_DIR}/web -Dbackupdir=${TRAVIS_BUILD_DIR}/backup -Dwebuser=${USER} -Dwebgroup="`id -g -n`"
  - cd ${TRAVIS_BUILD_DIR}/web; php ilios.php migrate

# Install Ilios 3 deps
  - if [ "$ILIOS_THREE" = true ]; then npm install -g bower; fi
  - if [ "$ILIOS_THREE" = true ]; then (cp ${TRAVIS_BUILD_DIR}/sfi/app/config/parameters.yml.travis ${TRAVIS_BUILD_DIR}/sfi/app/config/parameters.yml); fi
  - if [ "$ILIOS_THREE" = true ]; then (cd ${TRAVIS_BUILD_DIR}/sfi; pwd; composer install --no-interaction); fi

before_script:
#initialize symfony test db
  - if [ "$ILIOS_THREE" = true ]; then (cd ${TRAVIS_BUILD_DIR}/sfi; bin/console doctrine:database:create --env=test); fi
  - if [ "$ILIOS_THREE" = true ]; then (cd ${TRAVIS_BUILD_DIR}/sfi; bin/console doctrine:schema:create --env=test); fi

script:
  # Run Ilios 3 tests
  #- if [ "$ILIOS_THREE" = true ]; then (cd ${TRAVIS_BUILD_DIR}/sfi; bin/console doctrine:schema:validate); fi
  - if [ "$ILIOS_THREE" = true ]; then (cd ${TRAVIS_BUILD_DIR}/sfi; bin/console doctrine:schema:update --dump-sql); fi
  - if [ "$ILIOS_THREE" = true ]; then (cd ${TRAVIS_BUILD_DIR}/sfi; bin/phpunit); fi
  - if [ "$ILIOS_THREE" = true ]; then (cd ${TRAVIS_BUILD_DIR}/sfi; bin/phpcs --standard=app/phpcs.xml src); fi
