language: php

php:
  - "5.4"
  - "5.3"

env:
  global:
    # env variables for Sauce credentials, see https://saucelabs.com/opensource/travis
    - secure: "XWO/3KBLV8qf8qF1mRmyX8t+gSLLoyBCEAUz7xjL5X9cMlO+XxaUSLWKfWO42tHAOEoqmKha3cora4ukURn3M8Y9bYotkfWmIeYPtzhWfwK5m8sn9JnQreSFwID06KOavglfnXdIjy9zPnO1i/NsGwB++8g4gyVp9XUbqurGcF4="
    - secure: "GdhFXs/AwEXh7qUqJf4FQOUKnqD60Jg4JHSybiKX84lm+CMqzT3QQg8k2KqMxXKWICoflxGqM4WhqM2DfxCgUXdssKxPntcV6Xs+g8Vxj/vpRKSPO/HC5H0Ih8Mv7wNYn/ay5VPJFB9Tk2u7QP0IH3MGXYLj2dUVCVMUa7gtD4k="

addons:
  hosts:
    - precise64

install:
  # Install composer packages in the app root. This will set up phing.
  - composer install

before_script:
# Set up Sauce Connect if we have a Sauce username set
  - if [ "$SAUCE_USERNAME" ] ; then (curl -L https://gist.github.com/santiycr/5139565/raw/sauce_connect_setup.sh | bash); fi

# Provision web server for Behat tests
  - "sudo apt-get install -y --force-yes mysql-server apache2 libapache2-mod-php5 php5-mysql php5-ldap sendmail expect > /dev/null"
  - "sudo /usr/sbin/a2enmod rewrite && sudo /usr/sbin/a2enmod headers && sudo /usr/sbin/a2enmod ssl"
  - "sudo /bin/ln -s /etc/apache2/sites-available/default-ssl /etc/apache2/sites-enabled/000-default-ssl"
  - "(cd /etc/apache2/sites-enabled && sudo /usr/bin/find . -! -type d -exec /bin/sed -i '/<Directory \\/var\\/www\\/>/,/<\\/Directory>/ { s,AllowOverride None,AllowOverride All,}' {} \\;)"
  - "sudo /usr/bin/find /etc/apache2/sites-enabled -! -type d -exec /bin/sed -i \"s,/var/www,${PWD}/web,g\" {} \\;"
  - sudo sed -i -e "/DocumentRoot/i\ServerName precise64" /etc/apache2/sites-available/default
  - "sudo /etc/init.d/apache2 restart"

# Get Selenium standalone server and run it for Behat tests
  - "wget http://selenium.googlecode.com/files/selenium-server-standalone-2.39.0.jar"
  - "java -jar selenium-server-standalone-2.39.0.jar -role hub > /dev/null &"

# Install the Ilios PHP app locally for PHPUnit testing
  - bin/phing -q -propertyfile build.properties.sample -Dskip-prompt=true -Dskip-db-backup=true -Ddb.username=root -Ddb.password= -Ddb.group=ilios_test -Dencryption_key=lorem_ipsum -Ddeploydir=${PWD}/web -Dbackupdir=${PWD}/backup -Dwebuser=${USER} -Dwebgroup="`id -g -n`"

# Start Phantom for headless Behat tests
  - "phantomjs --webdriver=8080 --webdriver-selenium-grid-hub=http://127.0.0.1:4444 --ignore-ssl-errors=true > /dev/null &"

# Install Behat
  - composer install -d tests/behat

# Install PHPUnit
  - composer install -d tests/phpunit

script:
# Run PHPUnit tests
  - "${PWD}/tests/phpunit/bin/phpunit -c ${PWD}/tests/phpunit/default.phpunit.xml --include-path ${PWD}/tests/phpunit --exclude-group ldap tests/phpunit/Ilios"
# Because the PHPUnit tests unfortunately pollute the database, do a clean reinstall before running Behat tests.
  - bin/phing db-install -q -propertyfile build.properties.sample -Dskip-prompt=true -Dskip-db-backup=true -Ddb.username=root -Ddb.password= -Ddb.group=ilios_test -Dencryption_key=lorem_ipsum -Ddeploydir=${PWD}/web -Dbackupdir=${PWD}/backup -Dwebuser=${USER} -Dwebgroup="`id -g -n`"

# Run Behat tests on headless browsers
  - "(cd tests/behat && bin/behat --tags ~@ignore -p travis)"

# Run Behat tests on GUI browsers via Sauce
  - if [ "$SAUCE_USERNAME" ] ; then (cd tests/behat && bin/behat --tags ~@ignore -c sauce.yml); fi
