language: php
services: mysql
sudo: false

php:
  - "5.4"

cache:
  directories:
    - $HOME/.composer/cache

install:
  - composer install  --no-interaction -d ${TRAVIS_BUILD_DIR}
  - cp ${TRAVIS_BUILD_DIR}/app/config/parameters.yml.travis ${TRAVIS_BUILD_DIR}/app/config/parameters.yml

before_script:
#increase our PHP memory limit so test coverage will work
  - echo "memory_limit=2048M" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
#initialize symfony mysql db
  - bin/console doctrine:database:create --env=dev
  - bin/console doctrine:migrations:migrate  --env=dev --no-interaction
#initialize symfony sqlite test db
  - bin/console doctrine:database:create --env=test

script:
  - bin/phpcs --standard=app/phpcs.xml src
  - bin/phpunit --coverage-clover build/logs/clover.xml
  - bin/console doctrine:schema:validate --env=dev

after_script:
  - php bin/coveralls #send test coverage informatio to coveralls
#encrypted the IRC room chat.freenode.net##ilios so that it doesn't run on pull requests
notifications:
  irc:
    secure: "LN3o6qWNjtQepmrtRTEpFUoa9jFar6l5CDw1pwYzLSJOWc+q59tzbXyoKUlGat9/z+s79euUz2Pcg8XF0fotBwNKArPUOHH2Ti74JbZXNkEstPxgNe5CVqRkwvjlDvMeCJPOqxoc1xD6Ss/XNc5Tu414aIym2Zd4mJ0utmyBOUA="
