# PHP
# Test and package your PHP project.
# Add steps that run tests, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/php

variables:
  apiGroupTestCommand: vendor/bin/simple-phpunit -c phpunit.xml.dist --group

jobs:
- job: build
  pool:
    vmImage: 'Ubuntu-16.04'
  strategy:
    matrix:
      PHP72:
        PHP_VERSION: '7.2'
      PHP73:
        PHP_VERSION: '7.3'
  steps:
    - script: |
        sudo update-alternatives --set php /usr/bin/php$(PHP_VERSION)
        sudo update-alternatives --set phar /usr/bin/phar$(PHP_VERSION)
        sudo update-alternatives --set phpdbg /usr/bin/phpdbg$(PHP_VERSION)
        sudo update-alternatives --set php-cgi /usr/bin/php-cgi$(PHP_VERSION)
        sudo update-alternatives --set phar.phar /usr/bin/phar.phar$(PHP_VERSION)
        php -version
      displayName: 'Use PHP version $(PHP_VERSION)'

    - script: composer install --no-interaction --prefer-dist
      displayName: 'composer install'

- job: apiOne
  dependsOn: build
  variables:
    testGroup: api_1
  steps:
    - script: $(apiGroupTestCommand) $(testGroup)
      displayName: 'PHPUnit API 1'
- job: apiTwo
  dependsOn: build
  variables:
    testGroup: api_2
  steps:
    - script: $(apiGroupTestCommand) $(testGroup)
      displayName: 'PHPUnit API 2'
