# PHP
# Test and package your PHP project.
# Add steps that run tests, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/php

jobs:
- template: .azure/api-test-job-template.yaml
  parameters:
    testGroup: api_1
- template: .azure/api-test-job-template.yaml
  parameters:
    testGroup: api_2
- template: .azure/api-test-job-template.yaml
  parameters:
    testGroup: api_3
- template: .azure/api-test-job-template.yaml
  parameters:
    testGroup: api_4
- template: .azure/api-test-job-template.yaml
  parameters:
    testGroup: api_5
