# PHP
# Test and package your PHP project.
# Add steps that run tests, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/php

trigger:
- master

resources:
  containers:
    - container: mysql
      image: ilios/mysql
      ports:
        - 33060:3306
      env:
        MYSQL_RANDOM_ROOT_PASSWORD: yes
        MYSQL_USER: "ilios_user"
        MYSQL_PASSWORD: "ilios_password"
        MYSQL_DATABASE: ilios

variables:
  ILIOS_MAILER_URL: null://localhost
  ILIOS_LOCALE: en
  ILIOS_SECRET: ThisTokenIsNotSoSecretChangeIt
  ILIOS_FILE_SYSTEM_STORAGE_PATH: /tmp
  SYMFONY_DEPRECATIONS_HELPER: disabled
  IMAGE: 'Ubuntu-16.04'

jobs:
- job: publish_test_results
  dependsOn:
  - PHPUnit_cli
  - PHPUnit_model
  - PHPUnit_mesh_data_import
  - PHPUnit_all_other_tests
  - PHPUnit_api_1
  - PHPUnit_api_2
  - PHPUnit_api_3
  - PHPUnit_api_4
  - PHPUnit_api_5
  - PHPUnit_twice
  steps:
    - checkout: none #skip checking out the default repository resource
    - task: DownloadBuildArtifacts@0
      displayName: 'Download Test Reports'
      inputs:
        artifactName: BuildOutput
        downloadPath: $(System.DefaultWorkingDirectory)
    - task: PublishTestResults@2
      displayName: 'Publish Test Results'
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: '**/*.xml'
        searchFolder: "$(System.DefaultWorkingDirectory)/"
        mergeTestResults: true
- job: build_and_run_container
  pool:
    vmImage: $(IMAGE)
  dependsOn:
  - PHPUnit_api_1
  - PHPUnit_api_2
  - PHPUnit_api_3
  - PHPUnit_api_4
  - PHPUnit_api_5
  steps:
    - script: docker build -t ilios-php-apache-test .
    - script: docker run -d --name ilios-php-apache-test -e "ILIOS_SECRET=TravisSecret" ilios-php-apache-test
    - script: docker ps | grep -q ilios-php-apache-test
    - script: docker exec ilios-php-apache-test php /var/www/ilios/bin/console monitor:health
