# PHP
# Test and package your PHP project.
# Add steps that run tests, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/php

trigger:
- master

resources:
  containers:
    - container: mysql
      image: ilios/mysql
      ports:
        - 33060:3306
      env:
        MYSQL_RANDOM_ROOT_PASSWORD: yes
        MYSQL_USER: "ilios_user"
        MYSQL_PASSWORD: "ilios_password"
        MYSQL_DATABASE: ilios

variables:
  ILIOS_MAILER_URL: null://localhost
  ILIOS_LOCALE: en
  ILIOS_SECRET: ThisTokenIsNotSoSecretChangeIt
  ILIOS_FILE_SYSTEM_STORAGE_PATH: /tmp
  SYMFONY_DEPRECATIONS_HELPER: disabled
  IMAGE: 'Ubuntu-16.04'
