version: '3.5'
services:
  nginx:
    ports:
      - "8000:80"
  db:
    image: ilios/mysql-demo
  php:
    environment:
      - ILIOS_DATABASE_URL=mysql://ilios:ilios@db/ilios?serverVersion=8.0
      - ILIOS_REQUIRE_SECURE_CONNECTION=false
      - ILIOS_ERROR_CAPTURE_ENABLED=false
      - ILIOS_SEARCH_HOSTS=opensearch
      - ILIOS_FILE_SYSTEM_STORAGE_PATH=/tmp
    depends_on:
      - db
  messages:
    environment:
      - ILIOS_DATABASE_URL=mysql://ilios:ilios@db/ilios?serverVersion=8.0
      - ILIOS_ERROR_CAPTURE_ENABLED=false
      - ILIOS_SEARCH_HOSTS=opensearch
      - ILIOS_FILE_SYSTEM_STORAGE_PATH=/tmp
    depends_on:
        - db
  opensearch:
    image: ilios/opensearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
  redis:
    image: ilios/redis
    ports:
      - "6379:6379"