version: '3.8'
services:
  db:
    build:
      context: .
      target: mysql-demo
    ports:
      - "13306:3306"
  nginx:
    build:
      context: .
      target: nginx
    ports:
      - "8000:80"
    volumes:
      # The "cached" option has no effect on Linux but improves performance on Mac
      - ./:/srv/app:rw,cached
    depends_on:
      - php
  php:
    build:
      context: .
      target: fpm-dev
    environment:
      - ILIOS_DATABASE_URL=mysql://ilios:ilios@db/ilios?serverVersion=5.7
      - ILIOS_REQUIRE_SECURE_CONNECTION=false
      - ILIOS_ERROR_CAPTURE_ENABLED=false
      - ILIOS_ELASTICSEARCH_HOSTS=elasticsearch
      - ILIOS_FILE_SYSTEM_STORAGE_PATH=/tmp
    volumes:
      # The "cached" option has no effect on Linux but improves performance on Mac
      - ./:/srv/app:rw,cached
      # Remove the var/ directory from the bind-mount for better performance
      - /srv/app/var
    depends_on:
      - db
  messages:
    build:
      context: .
      target: consume-messages
    environment:
      - APP_ENV=dev
      - ILIOS_DATABASE_URL=mysql://ilios:ilios@db/ilios?serverVersion=5.7
      - ILIOS_ERROR_CAPTURE_ENABLED=false
      - ILIOS_FILE_SYSTEM_STORAGE_PATH=/tmp
      - ILIOS_ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
        - db
        - elasticsearch
    volumes:
      # The "cached" option has no effect on Linux but improves performance on Mac
      - ./:/srv/app:rw,cached
      # Remove the var/ directory from the bind-mount for better performance
      - /srv/app/var
  elasticsearch:
    build:
      context: .
      target: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
