version: '3.5'
services:
    db:
        image: ilios/mysql-demo
        ports:
            - "13306:3306"
#    nginx:
#        build:
#            context: .
#            target: nginx
#        environment:
#            - FPM_CONTAINERS=php:9000
#        ports:
#            - "8000:80"
#        volumes:
#            - ./:/var/www/ilios:delegated
#    php:
#        build:
#            context: .
#            target: fpm-dev
#        environment:
#            - ILIOS_DATABASE_URL=mysql://ilios:ilios@db/ilios?serverVersion=5.6
#            - ILIOS_REQUIRE_SECURE_CONNECTION=false
#            - ILIOS_ERROR_CAPTURE_ENABLED=false
#            - ILIOS_ELASTICSEARCH_HOSTS=elasticsearch
#            - ILIOS_FILE_SYSTEM_STORAGE_PATH=/tmp
#        volumes:
#            - ./:/var/www/ilios:delegated
    elasticsearch:
        build: ./docker/elasticsearch-dev
        environment:
            - discovery.type=single-node
            - http.cors.enabled=true
            - http.cors.allow-origin=http://localhost:1358
            - http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
            - http.cors.allow-credentials=true
            - http.max_content_length=10mb #matches the AWS ElasticSearch limit
        ports:
            - "9200:9200"
