version: '3.5'
services:
  nginx:
    image: ilios/nginx:v3
    environment:
      - FPM_CONTAINERS=php:9000
    depends_on:
      - php
  php:
    image: ilios/fpm:v3
  messages:
    image: ilios/consume-messages:v3
