version: '2.1'
services:
    db:
        image: ilios/mysql-demo
    web:
        image: ilios/php-apache-dev
        environment:
            - AP_ENV=dev
            - APP_DEBUG=true
            - ILIOS_DATABASE_URL=mysql://ilios:ilios@db/ilios
            - ILIOS_REQUIRE_SECURE_CONNECTION=false
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www/ilios:delegated