/courseobjectives:
  get:
    summary: Fetch all course objectives.
    parameters:
      - name: X-JWT-Authorization
        in: header
        description: API JWT Token
        required: true
        type: string
        default: Token XXX
      - name: offset
        in: query
        description: Offset
        required: false
        type: integer
      - name: limit
        in: query
        description: Limit Results
        required: false
        type: integer
      - name: order_by
        in: query
        description: Order by fields.  Must by an array ie. &order_by[name]=ASC&order_by[description]=DESC
        required: false
        type: array
        items:
          type: string
      - name: filters
        in: query
        description: Filter by fields. Must be an array ie. &filters[id]=3
        required: false
        type: array
        items:
          type: string
    tags:
      - CourseObjective
    responses:
      '200':
        description: An array of course objectives.
        schema:
          type: object
          properties:
            courseObjectives:
              type: array
              items:
                $ref: '#/definitions/CourseObjective'
  post:
    summary: Create course objectives.
    parameters:
      - name: X-JWT-Authorization
        in: header
        description: API JWT Token
        required: true
        type: string
        default: Token XXX
      - name: body
        in: body
        required: true
        schema:
          type: object
          properties:
            courseObjectives:
              type: array
              items:
                $ref: '#/definitions/CourseObjective'
    tags:
      - CourseObjective
    responses:
      '201':
        description: An array of newly created course objectives.
        schema:
          type: object
          properties:
            courseObjectives:
              type: array
              items:
                $ref: '#/definitions/CourseObjective'
      '400':
        description: Bad Request Data
      '403':
        description: Access Denied
/courseobjectives/{id}:
  get:
    summary: Fetch a single course objective.
    parameters:
      - name: X-JWT-Authorization
        in: header
        description: API JWT Token
        required: true
        type: string
        default: Token XXX
      - name: id
        in: path
        required: true
        description: id
        type: integer
    tags:
      - CourseObjective
    responses:
      '200':
        description: A single course objective.
        schema:
          type: object
          properties:
            courseObjectives:
              type: array
              items:
                $ref: '#/definitions/CourseObjective'
      '404':
        description: Not found
  put:
    summary: Updates a given course objective.
    parameters:
      - name: X-JWT-Authorization
        in: header
        description: API JWT Token
        required: true
        type: string
        default: Token XXX
      - name: id
        in: path
        required: true
        description: id
        type: integer
      - name: body
        in: body
        required: true
        schema:
          type: object
          properties:
            courseObjective:
              $ref: '#/definitions/CourseObjective'
    tags:
      - CourseObjective
    responses:
      '200':
        description: The updated course objective.
        schema:
          type: object
          properties:
            courseObjective:
              $ref: '#/definitions/CourseObjective'
      '400':
        description: Bad Request Data
      '403':
        description: Access Denied
      '404':
        description: Not Found
  delete:
    summary: Delete a given course objective.
    parameters:
      - name: X-JWT-Authorization
        in: header
        description: API JWT Token
        required: true
        type: string
        default: Token XXX
      - name: id
        in: path
        required: true
        description: id
        type: integer
    tags:
      - CourseObjective
    responses:
      '204':
        description: Course objective successfully deleted.
      '403':
        description: Access Denied
      '404':
        description: Not Found
      '500':
        description: Failed to delete entity (usually caused by non-cascading relationships)
