/meshdescriptors:
  get:
    summary: Fetch all Meshdescriptors
    parameters:
      - name: X-JWT-Authorization
        in: header
        description: API JWT Token
        required: true
        type: string
        default: Token XXX
      - name: offset
        in: query
        description: Offset
        required: false
        type: integer
      - name: limit
        in: query
        description: Limit Results
        required: false
        type: integer
      - name: order_by
        in: query
        description: Order by fields.  Must by an array ie. &order_by[name]=ASC&order_by[description]=DESC
        required: false
        type: array
        items:
          type: string
      - name: filters
        in: query
        description: Filter by fields. Must be an array ie. &filters[id]=3
        required: false
        type: array
        items:
          type: string
      - name: q
        in: query
        description: Find descriptors by searching for a string
        required: false
        type: string
    tags:
      - Meshdescriptors
    responses:
      '200':
        description: An array of meshdescriptors
        schema:
          type: object
          properties:
            meshdescriptors:
              type: array
              items:
                $ref: '#/definitions/Meshdescriptor'
/meshdescriptors/{id}:
  get:
    summary: Fetch a single Meshdescriptor
    parameters:
    - name: X-JWT-Authorization
      in: header
      description: API JWT Token
      required: true
      type: string
      default: Token XXX
    - name: id
      in: path
      required: true
      description: id
      type: integer
    tags:
      - Meshdescriptors
    responses:
      '200':
        description: A single Meshdescriptor
        schema:
          type: object
          properties:
            meshdescriptors:
              type: array
              items:
                $ref: '#/definitions/Meshdescriptor'
      '404':
        description: Not found
