/programyearobjectives:
  get:
    summary: Fetch all program year objectives.
    parameters:
      - name: X-JWT-Authorization
        in: header
        description: API JWT Token
        required: true
        type: string
        default: Token XXX
      - name: offset
        in: query
        description: Offset
        required: false
        type: integer
      - name: limit
        in: query
        description: Limit Results
        required: false
        type: integer
      - name: order_by
        in: query
        description: Order by fields.  Must by an array ie. &order_by[name]=ASC&order_by[description]=DESC
        required: false
        type: array
        items:
          type: string
      - name: filters
        in: query
        description: Filter by fields. Must be an array ie. &filters[id]=3
        required: false
        type: array
        items:
          type: string
    tags:
      - ProgramYearObjective
    responses:
      '200':
        description: An array of program year objectives.
        schema:
          type: object
          properties:
            programYearObjectives:
              type: array
              items:
                $ref: '#/definitions/ProgramYearObjective'
  post:
    summary: Create program year objectives.
    parameters:
      - name: X-JWT-Authorization
        in: header
        description: API JWT Token
        required: true
        type: string
        default: Token XXX
      - name: body
        in: body
        required: true
        schema:
          type: object
          properties:
            programYearObjectives:
              type: array
              items:
                $ref: '#/definitions/ProgramYearObjective'
    tags:
      - ProgramYearObjective
    responses:
      '201':
        description: An array of newly created program year objectives.
        schema:
          type: object
          properties:
            programYearObjectives:
              type: array
              items:
                $ref: '#/definitions/ProgramYearObjective'
      '400':
        description: Bad Request Data
      '403':
        description: Access Denied
/programyearobjectives/{id}:
  get:
    summary: Fetch a single program year objective.
    parameters:
      - name: X-JWT-Authorization
        in: header
        description: API JWT Token
        required: true
        type: string
        default: Token XXX
      - name: id
        in: path
        required: true
        description: id
        type: integer
    tags:
      - ProgramYearObjective
    responses:
      '200':
        description: A single program year objective.
        schema:
          type: object
          properties:
            programYearObjectives:
              type: array
              items:
                $ref: '#/definitions/ProgramYearObjective'
      '404':
        description: Not found
  put:
    summary: Updates a given program year objective.
    parameters:
      - name: X-JWT-Authorization
        in: header
        description: API JWT Token
        required: true
        type: string
        default: Token XXX
      - name: id
        in: path
        required: true
        description: id
        type: integer
      - name: body
        in: body
        required: true
        schema:
          type: object
          properties:
            programYearObjective:
              $ref: '#/definitions/ProgramYearObjective'
    tags:
      - ProgramYearObjective
    responses:
      '200':
        description: The updated program year objective.
        schema:
          type: object
          properties:
            programYearObjective:
              $ref: '#/definitions/ProgramYearObjective'
      '400':
        description: Bad Request Data
      '403':
        description: Access Denied
      '404':
        description: Not Found
  delete:
    summary: Delete a given program year objective.
    parameters:
      - name: X-JWT-Authorization
        in: header
        description: API JWT Token
        required: true
        type: string
        default: Token XXX
      - name: id
        in: path
        required: true
        description: id
        type: integer
    tags:
      - ProgramYearObjective
    responses:
      '204':
        description: Program year objective successfully deleted.
      '403':
        description: Access Denied
      '404':
        description: Not Found
      '500':
        description: Failed to delete entity (usually caused by non-cascading relationships)
