imports:
    - { resource: config.yml }
    - { resource: security.yml }

monolog:
    handlers:
        buffered:
            type:     buffer
            handler:  easylog
            channels: ["!event"]
            level:    debug
        easylog:
            type: service
            id:   easycorp.easylog.handler
        console:
            type: console
            process_psr_3_messages: false
            channels: ['!event', '!doctrine', '!console']
        # To follow logs in real time, execute the following command:
        # `bin/console server:log -vv`
        server_log:
            type: server_log
            process_psr_3_messages: false
            host: 127.0.0.1:9911
swiftmailer:
    disable_delivery: true

doctrine:
    dbal:
        url: '%env(ILIOS_DATABASE_URL)%'
        driver:   'pdo_mysql'
        server_version: '%env(ILIOS_DATABASE_MYSQL_VERSION)%'