imports:
    - { resource: config.yml }
    - { resource: security.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true
#    delivery_address: me@example.com

doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   pdo_sqlite
                path:     "%kernel.cache_dir%/test.db"
                logging: false
                profiling: false
monolog:
    handlers:
        main:
            type:   stream
            path:   "%kernel.logs_dir%/%kernel.environment%.log"
            level:  debug
        console:
            type:   console
            bubble: false

liip_functional_test:
    cache_sqlite_db: true

ilios_core:
    ldap_directory_url: null

ilios_authentication:
    type: "form"
