imports:
    - { resource: config.yml }
    - { resource: security.yml }

swiftmailer:
    disable_delivery: true

doctrine:
    dbal:
        url: '%env(ILIOS_DATABASE_URL)%'
        driver:   'pdo_mysql'
        server_version: '%env(ILIOS_DATABASE_MYSQL_VERSION)%'