parameters:
    env(ILIOS_DATABASE_HOST):
    env(ILIOS_DATABASE_PORT):
    env(ILIOS_DATABASE_NAME):
    env(ILIOS_DATABASE_USER):
    env(ILIOS_DATABASE_PASSWORD):
    env(ILIOS_DATABASE_MYSQL_VERSION):
    env(ILIOS_MAILER_TRANSPORT):
    env(ILIOS_MAILER_HOST):
    env(ILIOS_MAILER_USER):
    env(ILIOS_MAILER_PASSWORD):
    env(ILIOS_LOCALE):
    env(ILIOS_SECRET):

imports:
    - { resource: config.yml }
    - { resource: security.yml }
    - { resource: test-data-loaders.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   pdo_sqlite
                path:     "%kernel.cache_dir%/test.db"
                logging: false
                profiling: false

liip_functional_test:
    cache_db:
        sqlite: liip_functional_test.services_database_backup.sqlite
