imports:
    - { resource: services.yml }
    - { resource: "@AppBundle/Resources/config/config.yml" }
    - { resource: "@AppBundle/Resources/config/services.yml" }
    - { resource: "@AppBundle/Resources/config/dataloaders.yml" }
    - { resource: "@AppBundle/Resources/config/virtual-managers.yml" }

parameters:
    ilios_api_version: v1.34
    container.autowiring.strict_mode: true

framework:
    #esi:             ~
    #translator:      { fallbacks: ['%locale%'] }
    secret:          '%env(ILIOS_SECRET)%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form:            ~
    csrf_protection: false
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  '%env(ILIOS_LOCALE)%'
    trusted_hosts:   ~
    session:
        name: 'iliosapi'
        handler_id:  session.handler.native_file
        save_path:   '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments:       ~
    http_method_override: true
    serializer:
        enabled: false
    assets: ~
    php_errors:
      log: true
    web_link:
      enabled: true

# Twig Configuration
twig:
    debug:            '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    paths:
        '%kernel.root_dir%/../custom/email_templates': custom_email_templates
    exception_controller:  AppBundle\Controller\ExceptionController:showAction

# Doctrine Configuration
doctrine:
    dbal:
        charset:  UTF8

    orm:
      auto_generate_proxy_classes: '%kernel.debug%'
      auto_mapping: true
      metadata_cache_driver:
        type: service
        id: ilios.cache
      result_cache_driver:
        type: service
        id: ilios.cache
      query_cache_driver:
        type: service
        id: ilios.cache

# Swiftmailer Configuration
swiftmailer:
    transport: '%env(ILIOS_MAILER_TRANSPORT)%'
    host:      '%env(ILIOS_MAILER_HOST)%'
    username:  '%env(ILIOS_MAILER_USER)%'
    password:  '%env(ILIOS_MAILER_PASSWORD)%'
    spool:     { type: memory }

nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: ['*']
        allow_headers: ['*']
        allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
        expose_headers: ['*']
        max_age: 3600
    paths:
        '^/':

security:
    encoders:
        AppBundle\Classes\SessionUserInterface:
            algorithm: bcrypt
        ilios_legacy_encoder:
            id: AppBundle\Form\Encoder

doctrine_migrations:
    dir_name: '%kernel.root_dir%/Resources/DoctrineMigrations'
    name: Ilios Migrations
    namespace: Ilios\Migrations

exercise_html_purifier:
    default:
        Cache.SerializerPath: '%kernel.cache_dir%/htmlpurifier'
        HTML.Allowed: 'a[href|target],br,div,dd,dl,dt,em,li,ol,p,strong,sub,sup,ul,u'
        Attr.AllowedFrameTargets:
          - '_blank'


httplug:
    plugins:
        logger: ~
    clients:
        ga:
            factory: 'httplug.factory.guzzle6'
            plugins: ['httplug.plugin.logger']
            config:
                verify: true
                timeout: 10

happyr_google_analytics:
    tracking_id: 'INJECTED FROM Config IN TrackApiUsageListener'
    http_message_factory: 'httplug.message_factory'

liip_monitor:
    enable_controller: true
    default_group: default
    checks:
      groups:
        default:
          php_extensions: [apcu, mbstring, ldap, xml, dom, mysqlnd, pdo, zip, json, zlib]
          php_version:
            "7.2": ">="
          readable_directory: ["%kernel.cache_dir%"]
          writable_directory: ["%kernel.cache_dir%"]
#          Disabled for now as create_function throws warnings we should re-enabled once we move to SymfonyFlex where there is an update
#          symfony_requirements:
#            file:  '%kernel.root_dir%/../var/SymfonyRequirements.php'
          disk_usage:
            path: '%env(ILIOS_FILE_SYSTEM_STORAGE_PATH)%'
          security_advisory:
        production:
          doctrine_dbal: [default]
          doctrine_migrations:
            migrations_with_doctrine_bundle:
              connection: default
