imports:
    - { resource: config.yml }
    - { resource: security.yml }

monolog:
    handlers:
        main:
            type:         error_log
            action_level: debug
            handler:      nested
        nested:
            type:  stream
            path:  "php://stderr"
            level: debug
        console:
            type:  console
            process_psr_3_messages: false
