IliosAuthenticationBundle:
    resource: "@IliosAuthenticationBundle/Resources/config/routing.yml"
    prefix:   /auth

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

IliosCoreBundle:
    resource: "@IliosCoreBundle/Resources/config/routing.yml"
    prefix:   /api
    
ilios_core_uploadfile:
    path: /upload
    defaults:  { _controller: IliosCoreBundle:Upload:upload }

ilios_core_downloadlearningmaterial:
    pattern:     /lm/{token}
    defaults:
        _controller: IliosCoreBundle:Download:learningMaterial
    requirements:
        token: "^[a-zA-Z0-9]{64}$"

ilios_web:
    resource: "@IliosWebBundle/Resources/config/routing.yml"
    prefix:   /
