IliosAuthenticationBundle:
    resource: '@IliosAuthenticationBundle/Resources/config/routing.yml'
    prefix:   /auth

IliosApiBundle:
    resource: '@IliosApiBundle/Resources/config/routing.yml'
    prefix:   /api

ilios_apiinfo:
    path: /api
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    'AppBundle::apiinfo.html.twig'
        _format:     'html'
    
ilios_uploadfile:
    path: /upload
    defaults:  { _controller: AppBundle:Upload:upload }

ilios_downloadlearningmaterial:
    path:     /lm/{token}
    defaults:
        _controller: AppBundle:Download:learningMaterial
    requirements:
        token: '^[a-zA-Z0-9]{64}$'

ilios_downloadcurriculuminventoryreport:
    path:     /ci-report-dl/{token}
    defaults:
        _controller: AppBundle:CurriculumInventoryDownload:get
    requirements:
        token: '^[a-zA-Z0-9]{64}$'

_monitor:
    resource: "@LiipMonitorBundle/Resources/config/routing.xml"
    prefix: /ilios/health

app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /
