security:
    firewalls:
        default:
            pattern:    ^/
            stateless: true
            jwt: ~
            provider: ilios_database

    providers:
        ilios_database:
            entity:
                class: IliosCoreBundle:User
                property: id
