security:
    access_decision_manager:
      strategy: unanimous
    firewalls:
        api_docs:
            pattern:   ^/api/doc
            anonymous: ~
        anonymous_auth:
            pattern:    ^/(auth|application)/(login|config|logout)
            anonymous: ~
        authenticated_auth:
            pattern:    ^/auth
            stateless: true
            simple_preauth:
                authenticator: ilios_authentication.jwt.authenticator
            provider: ilios_user_entity
        authenticated_application:
            pattern:    ^/application
            stateless: true
            simple_preauth:
                authenticator: ilios_authentication.jwt.authenticator
            provider: ilios_user_entity
        upload:
            pattern:    ^/upload
            stateless: true
            simple_preauth:
                authenticator: ilios_authentication.jwt.authenticator
            provider: ilios_user_entity
        errors:
            pattern:    ^/errors
            stateless: true
            simple_preauth:
                authenticator: ilios_authentication.jwt.authenticator
            provider: ilios_user_entity
        default:
            pattern:    ^/api
            stateless: true
            simple_preauth:
                authenticator: ilios_authentication.jwt.authenticator
            provider: ilios_user_entity

    providers:
        ilios_user_entity:
            entity:
                class: IliosCoreBundle:User
                property: id
