security:
    firewalls:
        api_docs:
            pattern:   ^/api/doc
            anonymous: ~
        auth:
            pattern:    ^/auth
            stateless: true
            jwt: ~
            anonymous: ~
            provider: ilios_user_entity
        default:
            pattern:    ^/api
            stateless: true
            jwt: ~
            provider: ilios_user_entity

    providers:
        ilios_user_entity:
            entity:
                class: IliosCoreBundle:User
                property: id
