security:
    access_decision_manager:
      strategy: unanimous
    firewalls:
        api_docs:
            pattern:   ^/api/doc
            anonymous: ~
        anonymous_auth:
            pattern:    ^/(auth|application)/(login|config|logout)
            anonymous: ~
        authenticated_auth:
            pattern:    ^/auth
            stateless: true
            simple_preauth:
                authenticator: ilios_authentication.jwt.authenticator
            provider: session_user
        authenticated_application:
            pattern:    ^/application
            stateless: true
            simple_preauth:
                authenticator: ilios_authentication.jwt.authenticator
            provider: session_user
        upload:
            pattern:    ^/upload
            stateless: true
            simple_preauth:
                authenticator: ilios_authentication.jwt.authenticator
            provider: session_user
        errors:
            pattern:    ^/errors
            stateless: true
            simple_preauth:
                authenticator: ilios_authentication.jwt.authenticator
            provider: session_user
        default:
            pattern:    ^/api
            stateless: true
            simple_preauth:
                authenticator: ilios_authentication.jwt.authenticator
            provider: session_user
    providers:
        session_user:
            id: ilios_authentication.session_user_provider
