security:
    firewalls:
        api_docs:
            pattern:   ^/api/doc
            anonymous: ~
        authenticated_auth:
            pattern:    ^/auth/(whoami|refresh)
            stateless: true
            simple_preauth:
                authenticator: ilios_authentication.jwt.authenticator
            provider: ilios_user_entity
        anonymous_auth:
            pattern:    ^/auth/(login|config)
            anonymous: ~
        upload:
            pattern:    ^/upload
            stateless: true
            simple_preauth:
                authenticator: ilios_authentication.jwt.authenticator
            provider: ilios_user_entity
        default:
            pattern:    ^/api
            stateless: true
            simple_preauth:
                authenticator: ilios_authentication.jwt.authenticator
            provider: ilios_user_entity

    providers:
        ilios_user_entity:
            entity:
                class: IliosCoreBundle:User
                property: id
