services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Tests\AppBundle\DataLoader\:
            resource: '../../tests/AppBundle/DataLoader/*'