ilios_web_ics:
    path:     /ics/{key}
    defaults:
        _controller: IliosWebBundle:Ics:index
    requirements:
        key: "^[a-zA-Z0-9]{64}$"
ilios_web_config:
    path:     /application/config
    defaults:
        _controller: IliosWebBundle:Config:index
    methods: [GET]
ilios_web_errors:
    path:     /errors
    defaults:
        _controller: IliosWebBundle:Error:error
    methods:  [POST]
ilios_web_directory_search:
    path:     /application/directory/search
    defaults:
        _controller: IliosWebBundle:Directory:search
    methods: [GET]
ilios_web_directory_find:
    path:     /application/directory/find/{id}
    defaults:
        _controller: IliosWebBundle:Directory:find
    methods: [GET]
    requirements:
        key: '\d+'
ilios_web_homepage:
    path:     /{url}
    defaults:
        url: null
        _controller: IliosWebBundle:Index:index
    requirements:
        url: ".+"