Schoolconfig:
 type: object
 properties:
  id:
   description: Id
   type: integer
  name:
   description: Name
   type: string
  value:
   description: Value
   type: string
  school:
   description: School
   type: string
