monolog:
  handlers:
    main:
      type: stream
      path: "%kernel.logs_dir%/%kernel.environment%.log"
      level: debug
      channels: ["!event"]
    buffered:
      type:     buffer
      handler:  easylog
      channels: ["!event"]
      level:    debug
    easylog:
      type: service
      id:   EasyCorp\EasyLog\EasyLogHandler
    console:
      type: console
      process_psr_3_messages: false
      channels: ["!event", "!doctrine", "!console"]