# PHP
# Test and package your PHP project.
# Add steps that run tests, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/php

parameters:
  testGroup: ''

jobs:
- job: TestAPIGroup_${{ parameters.testGroup }}
  pool:
    vmImage: 'Ubuntu-16.04'
  strategy:
    matrix:
      PHP72:
        PHP_VERSION: '7.2'
      PHP73:
        PHP_VERSION: '7.3'
  steps:
  - bash: |
      if [ -z "$TEST_GROUP" ]; then
        echo "##vso[task.logissue type=error;]Missing template parameter \"testGroup\""
        echo "##vso[task.complete result=Failed;]"
      fi
    env:
      TEST_GROUP: ${{ parameters.testGroup }}
    displayName: Check for required parameters
  - template: ./install-steps-template.yaml
    parameters:
      phpVersion: $(PHP_VERSION)
  - script: vendor/bin/simple-phpunit -c phpunit.xml.dist --group ${{ parameters.testGroup }}
    displayName: PHPUnit $(PHP_VERSION) ${{ parameters.testGroup }}
