# PHP
# Test and package your PHP project.
# Add steps that run tests, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/php

parameters:
  testCommand: ''
  name: ''
  image: ''
  dependsOn:

jobs:
- job: PHPUnit_${{ parameters.name }}
  dependsOn: ${{ parameters.dependsOn }}
  pool:
    vmImage: 'Ubuntu-16.04'
  strategy:
    matrix:
      PHP72:
        PHP_VERSION: '7.2'
      PHP73:
        PHP_VERSION: '7.3'
  steps:
  - bash: |
      if [ -z "$TEST_COMMAND" ]; then
        echo "##vso[task.logissue type=error;]Missing template parameter \"testCommand\""
        echo "##vso[task.complete result=Failed;]"
      fi
    env:
      TEST_COMMAND: ${{ parameters.testCommand }}
    displayName: Check for required parameters
  - template: ./install-steps-template.yaml
    parameters:
      phpVersion: $(PHP_VERSION)
  - script: bin/phpunit -c phpunit.xml.dist ${{ parameters.testCommand }}
    displayName: PHPUnit $(PHP_VERSION) ${{ parameters.testCommand }}
