version: '3.5'
services:
    db:
        image: ilios/mysql-demo
        ports:
            - "13306:3306"
    web:
        build:
            context: ../
            target: nginx
        depends_on:
            - update-frontend
        ports:
            - "8000:80"
        volumes:
            - iliosData:/var/www/ilios
    fpm:
        build:
            context: ../
            target: fpm
        depends_on:
            - admin
            - update-frontend
            - migrate-database
        volumes:
            - iliosData:/var/www/ilios
        environment:
            - ILIOS_DATABASE_URL=mysql://ilios:ilios@db/ilios?serverVersion=5.6
            - ILIOS_ELASTICSEARCH_HOSTS=elasticsearch
            - ILIOS_FILE_SYSTEM_STORAGE_PATH=/tmp
    admin:
        build:
            context: ../
            target: admin
        volumes:
            - iliosData:/var/www/ilios
        environment:
            - ILIOS_DATABASE_URL=mysql://ilios:ilios@db/ilios?serverVersion=5.6
            - ILIOS_ELASTICSEARCH_HOSTS=elasticsearch
            - ILIOS_FILE_SYSTEM_STORAGE_PATH=/tmp
    update-frontend:
        build:
            context: ../
            target: update-frontend
        depends_on:
            - admin
        volumes:
            - iliosData:/var/www/ilios
        environment:
            - ILIOS_DATABASE_URL=mysql://ilios:ilios@db/ilios?serverVersion=5.6
            - ILIOS_ELASTICSEARCH_HOSTS=elasticsearch
            - ILIOS_FILE_SYSTEM_STORAGE_PATH=/tmp
    migrate-database:
        build:
            context: ../
            target: migrate-database
        depends_on:
            - admin
            - db
        volumes:
            - iliosData:/var/www/ilios
        environment:
            - ILIOS_DATABASE_URL=mysql://ilios:ilios@db/ilios?serverVersion=5.6
            - ILIOS_ELASTICSEARCH_HOSTS=elasticsearch
            - ILIOS_FILE_SYSTEM_STORAGE_PATH=/tmp
    consume-messages:
        build:
            context: ../
            target: consume-messages
        depends_on:
            - admin
            - db
        volumes:
            - iliosData:/var/www/ilios
        environment:
            - ILIOS_DATABASE_URL=mysql://ilios:ilios@db/ilios?serverVersion=5.6
            - ILIOS_ELASTICSEARCH_HOSTS=elasticsearch
            - ILIOS_FILE_SYSTEM_STORAGE_PATH=/tmp
    elasticsearch:
        build:
            context: ../
            target: elasticsearch
        environment:
            - discovery.type=single-node
        ports:
            - "9200:9200"
volumes:
    iliosData:
