/applicationconfigs:
      get:
        summary: Fetch all Applicationconfigs
        description: |
          Ilios Applicationconfigs
        parameters:
          - name: offset
            in: query
            description: Offset
            required: false
            type: number
            format: integer
          - name: limit
            in: query
            description: Limit Results
            required: false
            type: number
            format: integer
            default: 20
          - name: order_by
            in: query
            description: Order by fields.  Must by an array ie. &order_by[name]=ASC&order_by[description]=DESC
            required: false
            type: array
          - name: filters
            in: query
            description: Filter by fields. Must be an array ie. &filters[id]=3
            required: false
            type: array
        tags:
          - Applicationconfigs
        responses:
          200:
            description: An array of applicationconfigs
            schema:
              type: object
              properties:
                applicationconfigs:
                  type: array
                  items:
                    $ref: '#/definitions/Applicationconfig'
          default:
            description: Unexpected error
            schema:
              $ref: '#/definitions/Error'
      post:
        summary: Create a Applicationconfigs
        description: |
          Ilios Applicationconfigs
        parameters:
        - name: body
          in: body
          required: true
          schema:
              type: object
              properties:
                applicationconfig:
                  $ref: '#/definitions/Applicationconfig'
        tags:
          - Applicationconfigs
        responses:
          201:
            description: A single Applicationconfig
            schema:
              type: object
              properties:
                applicationconfigs:
                  type: array
                  items:
                    $ref: '#/definitions/Applicationconfig'
          default:
            description: Unexpected error
            schema:
              $ref: '#/definitions/Error'
/applicationconfigs/{id}:
  get:
    summary: Fetch a single Applicationconfig
    description: |
          Ilios Applicationconfig
    parameters:
    - name: id
      in: path
      required: true
      description: id
      type: integer
    tags:
      - Applicationconfigs
    responses:
      200:
        description: A single Applicationconfig
        schema:
          type: object
          properties:
            applicationconfigs:
              type: array
              items:
                $ref: '#/definitions/Applicationconfig'
      default:
        description: Unexpected error
        schema:
          $ref: '#/definitions/Error'
  put:
    summary: Edit a Applicationconfig
    description: |
      Ilios Applicationconfigs
    parameters:
    - name: id
      in: path
      required: true
      description: id
      type: integer
    - name: body
      in: body
      required: true
      schema:
          type: object
          properties:
            applicationconfig:
              $ref: '#/definitions/Applicationconfig'
    tags:
      - Applicationconfigs
    responses:
      200:
        description: A single Applicationconfig
        schema:
          type: object
          properties:
            applicationconfig:
              $ref: '#/definitions/Applicationconfig'
      default:
        description: Unexpected error
        schema:
          $ref: '#/definitions/Error'
  delete:
    summary: Delete Applicationconfig
    description: |
          Delete Ilios Applicationconfig
    tags:
      - Applicationconfigs
    responses:
      204:
        description: Deleted Applicationconfig
      default:
        description: Unexpected error
        schema:
          $ref: '#/definitions/Error'