/schoolconfigs:
      get:
        summary: Fetch all Schoolconfigs
        description: |
          Ilios Schoolconfigs
        parameters:
          - name: offset
            in: query
            description: Offset
            required: false
            type: number
            format: integer
          - name: limit
            in: query
            description: Limit Results
            required: false
            type: number
            format: integer
            default: 20
          - name: order_by
            in: query
            description: Order by fields.  Must by an array ie. &order_by[name]=ASC&order_by[description]=DESC
            required: false
            type: array
          - name: filters
            in: query
            description: Filter by fields. Must be an array ie. &filters[id]=3
            required: false
            type: array
        tags:
          - Schoolconfigs
        responses:
          200:
            description: An array of schoolconfigs
            schema:
              type: object
              properties:
                schoolconfigs:
                  type: array
                  items:
                    $ref: '#/definitions/Schoolconfig'
          default:
            description: Unexpected error
            schema:
              $ref: '#/definitions/Error'
      post:
        summary: Create a Schoolconfigs
        description: |
          Ilios Schoolconfigs
        parameters:
        - name: body
          in: body
          required: true
          schema:
              type: object
              properties:
                schoolconfig:
                  $ref: '#/definitions/Schoolconfig'
        tags:
          - Schoolconfigs
        responses:
          201:
            description: A single Schoolconfig
            schema:
              type: object
              properties:
                schoolconfigs:
                  type: array
                  items:
                    $ref: '#/definitions/Schoolconfig'
          default:
            description: Unexpected error
            schema:
              $ref: '#/definitions/Error'
/schoolconfigs/{id}:
  get:
    summary: Fetch a single Schoolconfig
    description: |
          Ilios Schoolconfig
    parameters:
    - name: id
      in: path
      required: true
      description: id
      type: integer
    tags:
      - Schoolconfigs
    responses:
      200:
        description: A single Schoolconfig
        schema:
          type: object
          properties:
            schoolconfigs:
              type: array
              items:
                $ref: '#/definitions/Schoolconfig'
      default:
        description: Unexpected error
        schema:
          $ref: '#/definitions/Error'
  put:
    summary: Edit a Schoolconfig
    description: |
      Ilios Schoolconfigs
    parameters:
    - name: id
      in: path
      required: true
      description: id
      type: integer
    - name: body
      in: body
      required: true
      schema:
          type: object
          properties:
            schoolconfig:
              $ref: '#/definitions/Schoolconfig'
    tags:
      - Schoolconfigs
    responses:
      200:
        description: A single Schoolconfig
        schema:
          type: object
          properties:
            schoolconfig:
              $ref: '#/definitions/Schoolconfig'
      default:
        description: Unexpected error
        schema:
          $ref: '#/definitions/Error'
  delete:
    summary: Delete Schoolconfig
    description: |
          Delete Ilios Schoolconfig
    parameters:
    - name: id
      in: path
      required: true
      description: id
      type: integer
    tags:
      - Schoolconfigs
    responses:
      204:
        description: Deleted Schoolconfig
      default:
        description: Unexpected error
        schema:
          $ref: '#/definitions/Error'