ilios_apiinfo:
  path: /api
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
  defaults:
    template:    'apiinfo.html.twig'
    _format:     'html'

_monitor:
  resource: "@LiipMonitorBundle/Resources/config/routing.xml"
  prefix: /ilios/health

ilios_swagger_redirect_docs:
  path: /api/docs/
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
  defaults:
    path: /api/doc/
    permanent: true

controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
