ilios_apiinfo:
  path: /api
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
  defaults:
    template:    'apiinfo.html.twig'
    _format:     'html'

app.swagger_ui:
  path: /api/doc
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

app.swagger:
  path: /api/doc.json
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.swagger }

_monitor:
  resource: "@LiipMonitorBundle/Resources/config/routing.xml"
  prefix: /ilios/health

ilios_swagger_redirect_docs:
  path: /api/docs/
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
  defaults:
    path: /api/doc/
    permanent: true

controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation
