parameters:
  locale: 'en'
  app.dataloader.auditlog.class: Tests\CliBundle\DataLoader\AuditLogData

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  App\Tests\DataLoader\:
    public: true
    resource: '%kernel.project_dir%/tests/DataLoader'

  App\Tests\Fixture\:
    resource: '%kernel.project_dir%/tests/Fixture'

  app.dataloader.auditlog:
    class: "%app.dataloader.auditlog.class%"

  # public in tests only for JsonControllerTest access
  App\Service\JsonWebTokenManager:
    public: true
    arguments:
      $kernelSecret: '%kernel.secret%'

  App\Repository\ApplicationConfigRepository:
    arguments:
      $cacheEnabled: false

  App\Tests\TestVersionProvider:
    arguments:
      $environment: '%kernel.environment%'
    tags:
      - { name: shivas_versioning.provider, alias: test_version_provider, priority: 0 }
