parameters:
  locale: 'en'
  app.dataloader.auditlog.class: Tests\CliBundle\DataLoader\AuditLogData

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  App\Tests\DataLoader\:
    public: true
    resource: '%kernel.project_dir%/tests/DataLoader'

  App\Tests\Fixture\:
    resource: '%kernel.project_dir%/tests/Fixture'

  app.dataloader.auditlog:
    class: "%app.dataloader.auditlog.class%"

  # public in tests only for JsonControllerTest access
  App\Service\JsonWebTokenManager:
    public: true
    arguments:
      $kernelSecret: '%kernel.secret%'

  App\Entity\Manager\ApplicationConfigManager:
    public: true
    arguments:
      $class: 'App\Entity\ApplicationConfig'
      $cacheEnabled: false
