ilios_api_currentsession:
    path:     /api/{version}/currentsession
    defaults: { _controller: App\Controller\CurrentSession::get }
    methods:  [GET]
    requirements:
        version: "%ilios_api_valid_api_versions%"

ilios_api_academicyear_get:
    path:     /api/{version}/{object}/{id}
    defaults: { _controller: App\Controller\AcademicYear::get }
    methods:  [GET]
    requirements:
        version: "%ilios_api_valid_api_versions%"
        object: 'academicyears'
        id: '\d+'

ilios_api_getallacademicyears:
    path:     /api/{version}/{object}
    defaults: { _controller: App\Controller\AcademicYear::getAll }
    methods:  [GET]
    requirements:
        version: "%ilios_api_valid_api_versions%"
        object: 'academicyears'

ilios_api_academicyear_404:
    path:     /api/{version}/{object}/{id}
    defaults: { _controller: App\Controller\AcademicYear::fourOhFour, id: 0 }
    methods:  [POST, PUT, DELETE]
    requirements:
        version: "%ilios_api_valid_api_versions%"
        object: 'academicyears'
        id: '(?i)[a-z0-9\-]+'

ilios_api_schoolevents:
    path:     /api/{version}/schoolevents/{id}
    defaults: { _controller: App\Controller\Schoolevent::get }
    methods:  [GET]
    requirements:
        version: "%ilios_api_valid_api_versions%"
        id: '\d+'

ilios_api_userevents:
    path:     /api/{version}/userevents/{id}
    defaults: { _controller: App\Controller\Userevent::get }
    methods:  [GET]
    requirements:
        version: "%ilios_api_valid_api_versions%"
        id: '\d+'

ilios_api_usermaterials:
    path:     /api/{version}/usermaterials/{id}
    defaults: { _controller: App\Controller\Usermaterial::get }
    methods:  [GET]
    requirements:
        version: "%ilios_api_valid_api_versions%"
        id: '\d+'