ilios_swagger_index:
    path:     /api/doc/
    defaults: { _controller: AppBundle:SwaggerDocs:index }
    methods:  [GET]

ilios_swagger_file:
    path:     /api/doc/swagger.yml
    defaults: { _controller: AppBundle:SwaggerDocs:yaml }
    methods:  [GET]

ilios_swagger_ui:
    path:     /api/doc/{fileName}
    requirements:
        fileName: .*
    defaults: { _controller: AppBundle:SwaggerDocs:ui }
    methods:  [GET]

ilios_api_non_entity_routes:
    resource: "@AppBundle/Resources/config/non-entity-routes.yml"

ilios_api_special_routes:
    resource: "@AppBundle/Resources/config/special-routes.yml"

ilios_api_get:
    path:     /api/{version}/{object}/{id}
    defaults: { _controller: AppBundle:Api:get }
    methods:  [GET]
    requirements:
        version: "%ilios_api_valid_api_versions%"
        object: '[a-z]+'
        id: '(?i)[a-z0-9\-]+'

ilios_api_getall:
    path:     /api/{version}/{object}
    defaults: { _controller: AppBundle:Api:getAll }
    methods:  [GET]
    requirements:
        version: "%ilios_api_valid_api_versions%"
        object: '[a-z]+'

ilios_api_post:
    path:     /api/{version}/{object}
    defaults: { _controller: AppBundle:Api:post }
    methods:  [POST]
    requirements:
        version: "%ilios_api_valid_api_versions%"
        object: '[a-z]+'

ilios_api_put:
    path:     /api/{version}/{object}/{id}
    defaults: { _controller: AppBundle:Api:put }
    methods:  [PUT]
    requirements:
        version: "%ilios_api_valid_api_versions%"
        object: '[a-z]+'
        id: '(?i)[a-z0-9\-]+'

ilios_api_delete:
    path:     /api/{version}/{object}/{id}
    defaults: { _controller: AppBundle:Api:delete }
    methods:  [DELETE]
    requirements:
        version: "%ilios_api_valid_api_versions%"
        object: '[a-z]+'
        id: '(?i)[a-z0-9\-]+'

api_bad_request:
    path:     /api/{url}
    defaults:
        url: null
        _controller: AppBundle:BadRequest:index
    requirements:
        url: ".+"

ilios_web_ics:
    path:     /ics/{key}
    defaults:
        _controller: AppBundle:Ics:index
    requirements:
        key: "^[a-zA-Z0-9]{64}$"
ilios_web_config:
    path:     /application/config
    defaults:
        _controller: AppBundle:Config:index
    methods: [GET]
ilios_web_errors:
    path:     /errors
    defaults:
        _controller: AppBundle:Error:error
    methods:  [POST]
ilios_web_directory_search:
    path:     /application/directory/search
    defaults:
        _controller: AppBundle:Directory:search
    methods: [GET]
ilios_web_directory_find:
    path:     /application/directory/find/{id}
    defaults:
        _controller: AppBundle:Directory:find
    methods: [GET]
    requirements:
        key: '\d+'
ilios_web_sw_registraton_js:
    path:     /sw-registration.js
    defaults:
        fileName: sw-registration.js
        _controller: AppBundle:Index:get
    requirements:
        fileName: ".+"
ilios_web_sw_js:
    path:     /sw.js
    defaults:
        fileName: sw.js
        _controller: AppBundle:Index:get
    requirements:
        fileName: ".+"
ilios_web_assets:
    path:     /{fileName}
    defaults:
        fileName: null
        versionedStaticFile: true
        _controller: AppBundle:Index:get
    requirements:
        fileName: ".+"