services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    AppBundle\:
            resource: '../../*'

    AppBundle\Controller\:
        resource: '../../Controller'
        public: true
        tags: ['controller.service_arguments']

    AppBundle\Command\UpdateFrontendCommand:
        arguments:
            $kernelCacheDir: '%kernel.cache_dir%'
            $kernelProjectDir: '%kernel.project_dir%'
            $apiVersion: '%ilios_api_version%'
            $environment: '%kernel.environment%'