ilios_core_apiinfo:
    path: /
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    'IliosCoreBundle::apiinfo.html.twig'
        _format:     'html'

api_aamcmethod_v1:
    resource: "@IliosCoreBundle/Controller/AamcMethodController.php"
    type:     rest
    prefix:   /v1
    defaults: {_format:json}


api_aamcpcrs_v1:
    resource: "@IliosCoreBundle/Controller/AamcPcrsController.php"
    type:     rest
    prefix:   /v1
    defaults: {_format:json}


api_alertchangetype_v1:
    resource: "@IliosCoreBundle/Controller/AlertChangeTypeController.php"
    type:     rest
    prefix:   /v1
    defaults: {_format:json}


api_alert_v1:
    resource: "@IliosCoreBundle/Controller/AlertController.php"
    type:     rest
    prefix:   /v1
    defaults: {_format:json}


api_apikey_v1:
    resource: "@IliosCoreBundle/Controller/ApiKeyController.php"
    type:     rest
    prefix:   /v1
    defaults: {_format:json}


api_assessmentoption_v1:
    resource: "@IliosCoreBundle/Controller/AssessmentOptionController.php"
    type:     rest
    prefix:   /v1
    defaults: {_format:json}


api_cisession_v1:
    resource: "@IliosCoreBundle/Controller/CISessionController.php"
    type:     rest
    prefix:   /v1
    defaults: {_format:json}


api_cohort_v1:
    resource: "@IliosCoreBundle/Controller/CohortController.php"
    type:     rest
    prefix:   /v1
    defaults: {_format:json}


api_competency_v1:
    resource: "@IliosCoreBundle/Controller/CompetencyController.php"
    type:     rest
    prefix:   /v1
    defaults: {_format:json}


api_courseclerkshiptype_v1:
    resource: "@IliosCoreBundle/Controller/CourseClerkshipTypeController.php"
    type:     rest
    prefix:   /v1
    defaults: {_format:json}


# api_courselearningmaterial_v1:
#    resource: "@IliosCoreBundle/Controller/CourseLearningMaterialController.php"
#    type:     rest
#    prefix:   /v1
#    defaults: {_format:json}


api_course_v1:
    resource: "@IliosCoreBundle/Controller/CourseController.php"
    type:     rest
    prefix:   /v1
    defaults: {_format:json}


api_curriculuminventoryacademiclevel_v1:
    resource: "@IliosCoreBundle/Controller/CurriculumInventoryAcademicLevelController.php"
    type:     rest
    prefix:   /v1
    defaults: {_format:json}


api_curriculuminventoryexport_v1:
    resource: "@IliosCoreBundle/Controller/CurriculumInventoryExportController.php"
    type:     rest
    prefix:   /v1
    defaults: {_format:json}


api_curriculuminventoryinstitution_v1:
    resource: "@IliosCoreBundle/Controller/CurriculumInventoryInstitutionController.php"
    type:     rest
    prefix:   /v1
    defaults: {_format:json}


api_curriculuminventoryreport_v1:
    resource: "@IliosCoreBundle/Controller/CurriculumInventoryReportController.php"
    type:     rest
    prefix:   /v1
    defaults: {_format:json}


api_curriculuminventorysequenceblock_v1:
    resource: "@IliosCoreBundle/Controller/CurriculumInventorySequenceBlockController.php"
    type:     rest
    prefix:   /v1
    defaults: {_format:json}


api_curriculuminventorysequenceblocksession_v1:
    resource: "@IliosCoreBundle/Controller/CurriculumInventorySequenceBlockSessionController.php"
    type:     rest
    prefix:   /v1
    defaults: {_format:json}


api_curriculuminventorysequence_v1:
    resource: "@IliosCoreBundle/Controller/CurriculumInventorySequenceController.php"
    type:     rest
    prefix:   /v1
    defaults: {_format:json}


api_department_v1:
    resource: "@IliosCoreBundle/Controller/DepartmentController.php"
    type:     rest
    prefix:   /v1
    defaults: {_format:json}


api_discipline_v1:
    resource: "@IliosCoreBundle/Controller/DisciplineController.php"
    type:     rest
    prefix:   /v1
    defaults: {_format:json}


api_group_v1:
    resource: "@IliosCoreBundle/Controller/GroupController.php"
    type:     rest
    prefix:   /v1
    defaults: {_format:json}


api_ilmsessionfacet_v1:
    resource: "@IliosCoreBundle/Controller/IlmSessionFacetController.php"
    type:     rest
    prefix:   /v1
    defaults: {_format:json}


api_ingestionexception_v1:
    resource: "@IliosCoreBundle/Controller/IngestionExceptionController.php"
    type:     rest
    prefix:   /v1
    defaults: {_format:json}

api_instructorgroup_v1:
    resource: "@IliosCoreBundle/Controller/InstructorGroupController.php"
    type:     rest
    prefix:   /v1
    defaults: {_format:json}


# #api_learningmaterialstatus_v1:
# #    resource: "@IliosCoreBundle/Controller/LearningMaterialStatusController.php"
# #    type:     rest
# #    prefix:   /v1
# #    defaults: {_format:json}
# #
# #
# #api_learningmaterialuserrole_v1:
# #    resource: "@IliosCoreBundle/Controller/LearningMaterialUserRoleController.php"
# #    type:     rest
# #    prefix:   /v1
# #    defaults: {_format:json}


api_meshconcept_v1:
    resource: "@IliosCoreBundle/Controller/MeshConceptController.php"
    type:     rest
    prefix:   /v1
    defaults: {_format:json}


api_meshdescriptor_v1:
    resource: "@IliosCoreBundle/Controller/MeshDescriptorController.php"
    type:     rest
    prefix:   /v1
    defaults: {_format:json}


api_meshpreviousindexing_v1:
    resource: "@IliosCoreBundle/Controller/MeshPreviousIndexingController.php"
    type:     rest
    prefix:   /v1
    defaults: {_format:json}


api_meshqualifier_v1:
    resource: "@IliosCoreBundle/Controller/MeshQualifierController.php"
    type:     rest
    prefix:   /v1
    defaults: {_format:json}


api_meshsemantictype_v1:
    resource: "@IliosCoreBundle/Controller/MeshSemanticTypeController.php"
    type:     rest
    prefix:   /v1
    defaults: {_format:json}


api_meshterm_v1:
    resource: "@IliosCoreBundle/Controller/MeshTermController.php"
    type:     rest
    prefix:   /v1
    defaults: {_format:json}


api_meshuserselection_v1:
    resource: "@IliosCoreBundle/Controller/MeshUserSelectionController.php"
    type:     rest
    prefix:   /v1
    defaults: {_format:json}


api_objective_v1:
    resource: "@IliosCoreBundle/Controller/ObjectiveController.php"
    type:     rest
    prefix:   /v1
    defaults: {_format:json}


api_offering_v1:
    resource: "@IliosCoreBundle/Controller/OfferingController.php"
    type:     rest
    prefix:   /v1
    defaults: {_format:json}


api_permission_v1:
    resource: "@IliosCoreBundle/Controller/PermissionController.php"
    type:     rest
    prefix:   /v1
    defaults: {_format:json}


api_program_v1:
    resource: "@IliosCoreBundle/Controller/ProgramController.php"
    type:     rest
    prefix:   /v1
    defaults: {_format:json}


api_programyear_v1:
    resource: "@IliosCoreBundle/Controller/ProgramYearController.php"
    type:     rest
    prefix:   /v1
    defaults: {_format:json}


api_programyearsteward_v1:
    resource: "@IliosCoreBundle/Controller/ProgramYearStewardController.php"
    type:     rest
    prefix:   /v1
    defaults: {_format:json}


api_publishevent_v1:
    resource: "@IliosCoreBundle/Controller/PublishEventController.php"
    type:     rest
    prefix:   /v1
    defaults: {_format:json}


api_recurringevent_v1:
    resource: "@IliosCoreBundle/Controller/RecurringEventController.php"
    type:     rest
    prefix:   /v1
    defaults: {_format:json}


api_report_v1:
    resource: "@IliosCoreBundle/Controller/ReportController.php"
    type:     rest
    prefix:   /v1
    defaults: {_format:json}


api_reportpovalue_v1:
    resource: "@IliosCoreBundle/Controller/ReportPoValueController.php"
    type:     rest
    prefix:   /v1
    defaults: {_format:json}


api_school_v1:
    resource: "@IliosCoreBundle/Controller/SchoolController.php"
    type:     rest
    prefix:   /v1
    defaults: {_format:json}


api_sessiondescription_v1:
    resource: "@IliosCoreBundle/Controller/SessionDescriptionController.php"
    type:     rest
    prefix:   /v1
    defaults: {_format:json}


api_sessionlearningmaterial_v1:
    resource: "@IliosCoreBundle/Controller/SessionLearningMaterialController.php"
    type:     rest
    prefix:   /v1
    defaults: {_format:json}


api_session_v1:
    resource: "@IliosCoreBundle/Controller/SessionController.php"
    type:     rest
    prefix:   /v1
    defaults: {_format:json}


api_sessiontype_v1:
    resource: "@IliosCoreBundle/Controller/SessionTypeController.php"
    type:     rest
    prefix:   /v1
    defaults: {_format:json}


api_usermadereminder_v1:
    resource: "@IliosCoreBundle/Controller/UserMadeReminderController.php"
    type:     rest
    prefix:   /v1
    defaults: {_format:json}


api_user_v1:
    resource: "@IliosCoreBundle/Controller/UserController.php"
    type:     rest
    prefix:   /v1
    defaults: {_format:json}


api_userrole_v1:
    resource: "@IliosCoreBundle/Controller/UserRoleController.php"
    type:     rest
    prefix:   /v1
    defaults: {_format:json}
