CalendarEvent:
 type: object
 properties:
  name:
   description: Name of the event
   type: string
   readOnly: true
  courseTitle:
   description: Title of the course
   type: string
   readOnly: true
  startDate:
   description: Start Date
   type: string
   format: date-time
   readOnly: true
  endDate:
   description: End Date
   type: string
   format: date-time
   readOnly: true
  offering:
   description: The ID of the offering this event belongs to
   type: integer
   readOnly: true
  ilmSession:
   description: The ID of the ILM Session this event belongs to
   type: integer
   readOnly: true
  color:
   description: Color to apply to an event
   type: string
   readOnly: true
  location:
   description: Location where the event will take place
   type: string
   readOnly: true
  url:
   description: Link to the virtual location where the event will take place
   type: string
   readOnly: true
  lastModified:
   description: The last time the details for this event were updated
   type: string
   format: date-time
   readOnly: true
  isPublished:
   description: Is this event published
   type: boolean
   readOnly: true
  isScheduled:
   description: Is this event published as TBD
   type: boolean
   readOnly: true
  instructors:
   description: UserIds of Instructors
   type: array
   readOnly: true
   items:
    type: integer
  attireRequired:
   description: Is special attire required by the attendee of this session
   type: boolean
   readOnly: true
  equipmentRequired:
   description: Is special equipment required by the attendee of this session
   type: boolean
   readOnly: true
  supplemental:
   description: Is this a supplemental session
   type: boolean
   readOnly: true
  attendanceRequired:
   description: Is attendance required at this session
   type: boolean
   readOnly: true
  session:
   description: ID of the session which this event belongs to
   type: integer
   readOnly: true
  course:
   description: ID of the course which this event belongs to
   type: integer
   readOnly: true
  courseExternalId:
   description: An external identifier of the course which this event belongs to
   type: string
   readOnly: true
  sessionTitle:
   description: Title of the session that this event belongs to
   type: string
   readOnly: true
  sessionDescription:
   description: Description of the session that this event belongs to
   type: string
   readOnly: true
  instructionalNotes:
   description: Instructional notes of the session that this event belongs to
   type: string
   readOnly: true
  sessionTypeId:
   description: ID of the session-type of the session that this event belongs to
   type: int
   readOnly: true
  sessionTypeTitle:
   description: Title of the session-type of the session that this event belongs to
   type: string
   readOnly: true
  school:
   description: School ID
   type: integer
   readOnly: true
  learningMaterials:
   description: Attached learning materials.
   type: array
   readOnly: true
   items:
    $ref: '#/definitions/UserMaterial'
  sessionObjectives:
   description: Linked session objectives
   type: array
   readOnly: true
   items:
    $ref: '#/definitions/SessionObjective'
  courseObjectives:
   description: Linked course objectives
   type: array
   readOnly: true
   items:
    $ref: '#/definitions/CourseObjective'
  competencies:
   description: Linked competencies
   type: array
   readOnly: true
   items:
    $ref: '#/definitions/Competency'
  sessionTerms:
    description: Vocabulary terms linked to the session that this event belongs to
    type: array
    readOnly: true
    items:
     $ref: '#/definitions/Term'
  courseTerms:
   description: Vocabulary terms linked to the course that this event belongs to
   type: array
   readOnly: true
   items:
    $ref: '#/definitions/Term'
