CourseObjective:
  type: object
  properties:
    id:
      description: Id
      type: integer
      readOnly: true
    title:
      description: Title
      type: string
    position:
      description: Position
      type: integer
    active:
      description: Active
      type: boolean
    course:
      description: Course
      type: string
    ancestor:
      description: Ancestor
      type: string
    descendants:
      description: Descendants
      type: array
      items:
        type: string
    terms:
      description: Terms
      type: array
      items:
        type: string
    sessionObjectives:
      description: Session objectives
      type: array
      items:
        type: string
    programYearObjectives:
      description: Program-year objectives
      type: array
      items:
        type: string
    meshDescriptors:
      description: Meshdescriptors
      type: array
      items:
        type: string
