Learnergroup:
 type: object
 properties:
  id:
   description: Id
   type: integer
   readOnly: true
  title:
   description: Title
   type: string
  location:
   description: Location
   type: string
  url:
   description: URL
   type: string
  needsAccomodation:
   description: Flag indicating whether this group needs to accomodate for disabilities in learning activities.
   type: boolean
  cohort:
   description: Cohort
   type: string
  parent:
   description: Parent
   type: string
  ancestor:
   description: Ancestor
   type: string
  descendants:
   description: Descendants
   type: array
   items:
    type: string
  children:
   description: Children
   type: array
   items:
    type: string
  ilmSessions:
   description: Ilmsessions
   type: array
   items:
    type: string
  offerings:
   description: Offerings
   type: array
   items:
    type: string
  instructorGroups:
   description: Instructorgroups
   type: array
   items:
    type: string
  users:
   description: Users
   type: array
   items:
    type: string
  instructors:
   description: Instructors
   type: array
   items:
    type: string
