ProgramYearObjective:
  type: object
  properties:
    id:
      description: Id
      type: integer
      readOnly: true
    title:
      description: Title
      type: string
    position:
      description: Position
      type: integer
    active:
      description: Active
      type: boolean
    programYear:
      description: Program-year
      type: string
    competency:
      description: Competency
      type: string
    ancestor:
      description: Ancestor
      type: string
    descendants:
      description: Descendants
      type: array
      items:
        type: string
    terms:
      description: Terms
      type: array
      items:
        type: string
    courseObjectives:
      description: Course objectives
      type: array
      items:
        type: string
    meshDescriptors:
      description: Meshdescriptors
      type: array
      items:
        type: string

