Programyear:
 type: object
 properties:
  id:
   description: Id
   type: integer
   readOnly: true
  startYear:
   description: Startyear
   type: integer
  locked:
   description: Locked
   type: boolean
  archived:
   description: Archived
   type: boolean
  program:
   description: Program
   type: string
  cohort:
   description: Cohort
   type: string
  directors:
   description: Directors
   type: array
   items:
    type: string
  competencies:
   description: Competencies
   type: array
   items:
    type: string
  terms:
   description: Terms
   type: array
   items:
    type: string
  programYearObjectives:
   description: Program-year objectives
   type: array
   items:
    type: string
