Schoolevent:
  type: object
  allOf:
    - $ref: '#/definitions/CalendarEvent'
  properties:
    school:
      description: School ID
      type: integer
      readOnly: true
    postrequisites:
      description: Postrequisites of this event.
      type: array
      readOnly: true
      items:
        $ref: '#/definitions/Schoolevent'
    prerequisites:
      description: Prerequisites to this event.
      type: array
      readOnly: true
      items:
        $ref: '#/definitions/Schoolevent'
