Userevent:
  type: object
  allOf:
    - $ref: '#/definitions/CalendarEvent'
  properties:
    postrequisites:
      description: Postrequisites of this event.
      type: array
      readOnly: true
      items:
        $ref: '#/definitions/Userevent'
    prerequisites:
      description: Prerequisites to this event.
      type: array
      readOnly: true
      items:
        $ref: '#/definitions/Userevent'
