version: 1

update_configs:
  - package_manager: php:composer
    directory: "/"
    update_schedule: daily
    ignored_updates:
      - match:
          dependency_name: "symfony/*"
    automerged_updates:
      - match:
          dependency_name: "elasticsearch/elasticsearch"
          update_type: "semver:minor"
      - match:
          dependency_type: all
          update_type: all

