services:
    security.access.dto.course_voter:
        class: Ilios\AuthenticationBundle\Voter\DTO\CourseDTOVoter
        parent: security.access.course_voter
        public: false
        tags:
            - { name: security.voter }
    security.access.dto.sesision_voter:
        class: Ilios\AuthenticationBundle\Voter\DTO\SessionDTOVoter
        parent: security.access.course_voter
        public: false
        tags:
            - { name: security.voter }
    security.access.dto.term_voter:
        class: Ilios\AuthenticationBundle\Voter\DTO\TermDTOVoter
        parent: security.access.entity.term_voter
        public: false
        tags:
            - { name: security.voter }
    security.access.dto.user_voter:
        class: Ilios\AuthenticationBundle\Voter\DTO\UserDTOVoter
        parent: security.access.entity.user_voter
        public: false
        tags:
            - { name: security.voter }
