services:
    security.access.dto.aamc_method_voter:
        class: Ilios\AuthenticationBundle\Voter\DTO\AamcMethodDTOVoter
        public: false
        tags:
            - { name: security.voter }
    security.access.dto.aamc_pcrs_voter:
        class: Ilios\AuthenticationBundle\Voter\DTO\AamcPcrsDTOVoter
        public: false
        tags:
            - { name: security.voter }
    security.access.dto.aamc_resource_type_voter:
        class: Ilios\AuthenticationBundle\Voter\DTO\AamcResourceTypeDTOVoter
        public: false
        tags:
            - { name: security.voter }
    security.access.dto.alert_change_type_voter:
        class: Ilios\AuthenticationBundle\Voter\DTO\AlertChangeTypeDTOVoter
        public: false
        tags:
            - { name: security.voter }
    security.access.dto.alert_voter:
        class: Ilios\AuthenticationBundle\Voter\DTO\AlertDTOVoter
        public: false
        tags:
            - { name: security.voter }
    security.access.dto.application_config_voter:
        class: Ilios\AuthenticationBundle\Voter\DTO\ApplicationConfigDTOVoter
        public: false
        tags:
            - { name: security.voter }
    security.access.dto.assessment_option_voter:
        class: Ilios\AuthenticationBundle\Voter\DTO\AssessmentOptionDTOVoter
        public: false
        tags:
            - { name: security.voter }
    security.access.dto.authentication_voter:
        class: Ilios\AuthenticationBundle\Voter\DTO\AuthenticationDTOVoter
        public: false
        tags:
            - { name: security.voter }
    security.access.dto.cohort_voter:
        class: Ilios\AuthenticationBundle\Voter\DTO\CohortDTOVoter
        parent: security.access.course_voter
        public: false
        tags:
            - { name: security.voter }
    security.access.dto.competency_voter:
        class: Ilios\AuthenticationBundle\Voter\DTO\CompetencyDTOVoter
        public: false
        tags:
            - { name: security.voter }
    security.access.dto.course_voter:
        class: Ilios\AuthenticationBundle\Voter\DTO\CourseDTOVoter
        parent: security.access.course_voter
        public: false
        tags:
            - { name: security.voter }
    security.access.dto.course_clerkship_type_voter:
        class: Ilios\AuthenticationBundle\Voter\DTO\CourseClerkshipTypeDTOVoter
        public: false
        tags:
            - { name: security.voter }
    security.access.dto.course_learning_material_voter:
        class: Ilios\AuthenticationBundle\Voter\DTO\CourseLearningMaterialDTOVoter
        parent: security.access.dto.course_voter
        public: false
        tags:
            - { name: security.voter }
    security.access.dto.curriculum_inventory_academic_level_voter:
        class: Ilios\AuthenticationBundle\Voter\DTO\CurriculumInventoryAcademicLevelDTOVoter
        parent: security.access.dto.curriculum_inventory_report_voter
        public: false
        tags:
            - { name: security.voter }
    security.access.dto.curriculum_inventory_institution_voter:
        class: Ilios\AuthenticationBundle\Voter\DTO\CurriculumInventoryInstitutionDTOVoter
        public: false
        tags:
            - { name: security.voter }
    security.access.dto.curriculum_inventory_report_voter:
        class: Ilios\AuthenticationBundle\Voter\DTO\CurriculumInventoryReportDTOVoter
        public: false
        tags:
            - { name: security.voter }
    security.access.dto.curriculum_inventory_sequence_voter:
        class: Ilios\AuthenticationBundle\Voter\DTO\CurriculumInventorySequenceDTOVoter
        parent: security.access.dto.curriculum_inventory_report_voter
        public: false
        tags:
            - { name: security.voter }
    security.access.dto.curriculum_inventory_sequence_block_voter:
        class: Ilios\AuthenticationBundle\Voter\DTO\CurriculumInventorySequenceBlockDTOVoter
        parent: security.access.dto.curriculum_inventory_report_voter
        public: false
        tags:
            - { name: security.voter }
    security.access.dto.department_voter:
        class: Ilios\AuthenticationBundle\Voter\DTO\DepartmentDTOVoter
        public: false
        tags:
            - { name: security.voter }
    security.access.dto.ilm_session_voter:
        class: Ilios\AuthenticationBundle\Voter\DTO\IlmSessionDTOVoter
        parent: security.access.course_voter
        public: false
        tags:
            - { name: security.voter }
    security.access.dto.ingestion_exception_voter:
        class: Ilios\AuthenticationBundle\Voter\DTO\IngestionExceptionDTOVoter
        public: false
        tags:
            - { name: security.voter }
    security.access.dto.learner_group_voter:
        class: Ilios\AuthenticationBundle\Voter\DTO\LearnerGroupDTOVoter
        public: false
        tags:
            - { name: security.voter }
    security.access.dto.mesh_descriptor_voter:
        class: Ilios\AuthenticationBundle\Voter\DTO\MeshDescriptorDTOVoter
        parent: security.access.entity.mesh_voter
        public: false
        tags:
            - { name: security.voter }
    security.access.dto.objective_voter:
        class: Ilios\AuthenticationBundle\Voter\DTO\ObjectiveDTOVoter
        public: false
        tags:
            - { name: security.voter }
    security.access.dto.offering_voter:
        class: Ilios\AuthenticationBundle\Voter\DTO\OfferingDTOVoter
        parent: security.access.dto.course_voter
        tags:
            - { name: security.voter }
    security.access.dto.program_voter:
        class: Ilios\AuthenticationBundle\Voter\DTO\ProgramDTOVoter
        public: false
        tags:
            - { name: security.voter }
    security.access.dto.program_year_voter:
        class: Ilios\AuthenticationBundle\Voter\DTO\ProgramYearDTOVoter
        parent: security.access.entity.program_year_voter
        public: false
        tags:
            - { name: security.voter }
    security.access.dto.school_voter:
        class: Ilios\AuthenticationBundle\Voter\DTO\SchoolDTOVoter
        public: false
        tags:
            - { name: security.voter }
    security.access.dto.session_voter:
        class: Ilios\AuthenticationBundle\Voter\DTO\SessionDTOVoter
        parent: security.access.course_voter
        public: false
        tags:
            - { name: security.voter }
    security.access.dto.session_type_voter:
        class: Ilios\AuthenticationBundle\Voter\DTO\SessionTypeDTOVoter
        public: false
        tags:
            - { name: security.voter }
    security.access.dto.term_voter:
        class: Ilios\AuthenticationBundle\Voter\DTO\TermDTOVoter
        parent: security.access.entity.term_voter
        public: false
        tags:
            - { name: security.voter }
    security.access.dto.user_voter:
        class: Ilios\AuthenticationBundle\Voter\DTO\UserDTOVoter
        parent: security.access.entity.user_voter
        public: false
        tags:
            - { name: security.voter }
