services:
    security.access.dto.course_voter:
        class: Ilios\AuthenticationBundle\Voter\DTO\CourseDTOVoter
        parent: security.access.course_voter
        public: false
        tags:
            - { name: security.voter }
    security.access.dto.sesision_voter:
        class: Ilios\AuthenticationBundle\Voter\DTO\SessionDTOVoter
        parent: security.access.course_voter
        public: false
        tags:
            - { name: security.voter }
