services:
    security.access.entity.course_voter:
        class: Ilios\AuthenticationBundle\Voter\Entity\CourseEntityVoter
        parent: security.access.course_voter
        public: false
        tags:
            - { name: security.voter }
    security.access.entity.session_voter:
        class: Ilios\AuthenticationBundle\Voter\Entity\SessionEntityVoter
        parent: security.access.course_voter
        public: false
        tags:
            - { name: security.voter }
