services:
    ilios_authentication.jwt_authenticator:
        class:  Ilios\AuthenticationBundle\Authenticator\Jwt
        public: false
    ilios_authentication.fix_header_listener:
        class: Ilios\AuthenticationBundle\Listener\AuthenticationHeader
        tags:
          - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 255 }
    ilios_authentication.jwt.listener:
        class: Ilios\AuthenticationBundle\Jwt\Listener
        arguments: ["@security.token_storage", "@security.authentication.manager", "%kernel.secret%"]
    ilios_authentication.jwt.provider:
        class: Ilios\AuthenticationBundle\Jwt\Provider
        arguments: [""]
    ilios_authentication.jwt.add_header:
        class: Ilios\AuthenticationBundle\Listener\AddJwtHeader
        arguments: ["@security.token_storage"]
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }
    ilios_authentication.form.legacy_encoder:
        class: Ilios\AuthenticationBundle\Form\Encoder
        arguments: ["%ilios_authentication.legacy_salt%"]
    ilios_authentication.shibboleth.authentication:
        class: Ilios\AuthenticationBundle\Shibboleth\Authentication
        scope: request
        arguments: ["@request", "@ilioscore.authentication.manager"]
    security.access.aamc_method_voter:
        class: Ilios\AuthenticationBundle\Voter\AamcMethodVoter
        public: false
        tags:
           - { name: security.voter }
    security.access.aamc_pcrs_voter:
        class: Ilios\AuthenticationBundle\Voter\AamcPcrsVoter
        public: false
        tags:
           - { name: security.voter }
    security.access.alert_change_type_voter:
        class: Ilios\AuthenticationBundle\Voter\AlertChangeTypeVoter
        public: false
        tags:
           - { name: security.voter }
    security.access.course_voter:
        class: Ilios\AuthenticationBundle\Voter\CourseVoter
        public: false
        tags:
            - { name: security.voter }
    security.access.curriculum_inventory_academic_level_voter:
        class: Ilios\AuthenticationBundle\Voter\CurriculumInventoryAcademicLevelVoter
        public: false
        tags:
           - { name: security.voter }
    security.access.curriculum_inventory_export_voter:
        class: Ilios\AuthenticationBundle\Voter\CurriculumInventoryExportVoter
        public: false
        tags:
           - { name: security.voter }
    security.access.curriculum_inventory_institution_voter:
        class: Ilios\AuthenticationBundle\Voter\CurriculumInventoryInstitutionVoter
        public: false
        tags:
           - { name: security.voter }
    security.access.curriculum_inventory_report_voter:
        class: Ilios\AuthenticationBundle\Voter\CurriculumInventoryReportVoter
        public: false
        tags:
           - { name: security.voter }
    security.access.curriculum_sequence_block_session_voter:
        class: Ilios\AuthenticationBundle\Voter\CurriculumInventorySequenceBlockSessionVoter
        public: false
        tags:
           - { name: security.voter }
    security.access.curriculum_sequence_block_voter:
        class: Ilios\AuthenticationBundle\Voter\CurriculumInventorySequenceBlockVoter
        public: false
        tags:
           - { name: security.voter }
    security.access.curriculum_sequence_voter:
        class: Ilios\AuthenticationBundle\Voter\CurriculumInventorySequenceVoter
        public: false
        tags:
           - { name: security.voter }
    security.access.school_voter:
        class: Ilios\AuthenticationBundle\Voter\SchoolVoter
        public: false
        tags:
            - { name: security.voter }
