services:
    ilios_authentication.jwt_authenticator:
        class:  Ilios\AuthenticationBundle\Authenticator\Jwt
        public: false
    ilios_authentication.fix_header_listener:
        class: Ilios\AuthenticationBundle\Listener\AuthenticationHeader
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 255 }
    ilios_authentication.jwt.listener:
        class: Ilios\AuthenticationBundle\Jwt\Listener
        arguments: ["@security.token_storage", "@security.authentication.manager", "%kernel.secret%"]
    ilios_authentication.jwt.provider:
        class: Ilios\AuthenticationBundle\Jwt\Provider
        arguments: [""]
    ilios_authentication.jwt.add_header:
        class: Ilios\AuthenticationBundle\Listener\AddJwtHeader
        arguments: ["@security.token_storage"]
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }
    ilios_authentication.jwt.manager:
        class: Ilios\AuthenticationBundle\Service\JsonWebTokenManager
        arguments: ["%kernel.secret%"]
    ilios_authentication.form.legacy_encoder:
        class: Ilios\AuthenticationBundle\Form\Encoder
        arguments: ["%ilios_authentication.legacy_salt%"]
    ilios_authentication.form.authentication:
        class: Ilios\AuthenticationBundle\Service\FormAuthentication
        arguments: ["@ilioscore.authentication.manager", "@security.password_encoder", "@security.token_storage","@ilios_authentication.jwt.manager"]
    ilios_authentication.shibboleth.authentication:
        class: Ilios\AuthenticationBundle\Service\ShibbolethAuthentication
        arguments: ["@ilioscore.authentication.manager", "@security.token_storage","@ilios_authentication.jwt.manager"]
