services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Ilios\AuthenticationBundle\:
          resource: '../../*'
