services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Ilios\AuthenticationBundle\:
            resource: '../../*'

    Ilios\AuthenticationBundle\Controller\:
        resource: '../../Controller'
        public: true
        tags: ['controller.service_arguments']

    Ilios\AuthenticationBundle\Listener\AddJwtHeader:
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }

    Ilios\AuthenticationBundle\Service\JsonWebTokenManager:
        public: true
        arguments:
          $secretKey: '%kernel.secret%'

    Ilios\AuthenticationBundle\Form\Encoder:
        arguments:
          $salt: '%ilios_authentication.legacy_salt%'

    Ilios\AuthenticationBundle\Service\CasAuthentication:
        public: true

    Ilios\AuthenticationBundle\Service\FormAuthentication:
        public: true

    Ilios\AuthenticationBundle\Service\ShibbolethAuthentication:
        public: true
        arguments:
          $logoutPath: '%ilios_authentication.shibboleth.logout_path%'
          $userIdAttribute: '%ilios_authentication.shibboleth.user_id_attribute%'

    Ilios\AuthenticationBundle\Service\LdapAuthentication:
        public: true
        arguments:
          $ldapHost: '%ilios_authentication.ldap.host%'
          $ldapPort: '%ilios_authentication.ldap.port%'
          $ldapBindTemplate: '%ilios_authentication.ldap.bind_template%'

    Ilios\AuthenticationBundle\Service\AuthenticationFactory:
        arguments:
          $authenticationServiceName: '%ilios_authentication.authenticatorservice%'

    Ilios\AuthenticationBundle\Service\AuthenticationInterface:
        factory: ['@Ilios\AuthenticationBundle\Service\AuthenticationFactory', createAuthenticationService]

    Ilios\AuthenticationBundle\Service\CasManager:
        arguments:
          $casServer: '%ilios_authentication.cas.server%'
          $casVersion: '%ilios_authentication.cas.version%'
          $casVerifySSL: '%ilios_authentication.cas.verifySSL%'
          $casCertificatePath: '%ilios_authentication.cas.certificatepath%'