parameters:
  ilios_api_valid_endpoints: >-
    aamcmethods,aamcpcrs,aamcresourcetypes,alertchangetypes,alerts,applicationconfigs,assessmentoptions,authentications,
    cohorts,competencies,courses,courseclerkshiptypes,courselearningmaterials,curriculuminventoryacademiclevels,curriculuminventoryexports,
    curriculuminventoryinstitutions,curriculuminventorysequenceblocks,curriculuminventorysequences,curriculuminventoryreports,
    departments,ilmsessions,ingestionexceptions,instructorgroups,learnergroups,learningmaterialstatuses,learningmaterialuserroles,
    meshconcepts,meshterms,offerings,programyears,sessions,schools,users
  ilios_api_non_dto_controllers: >-
    (?i)(applicationconfigs|courseclerkshiptypes|courselearningmaterials|curriculuminventoryacademiclevels|curriculuminventoryexports|curriculuminventoryinstitutions|curriculuminventorysequenceblocks|curriculuminventoryreports|curriculuminventorysequences|departments|ilmsessions|ingestionexceptions|instructorgroups|learningmaterialstatuses|learningmaterialuserroles|meshconcepts|meshterms|objectives|offerings|sessiondescriptions|sessionlearningmaterials)
