parameters:
  ilios_api_valid_endpoints: >-
    aamcmethods,aamcpcrs,aamcresourcetypes,alertchangetypes,alerts,applicationconfigs,assessmentoptions,authentications,
    cohorts,competencies,courses,courseclerkshiptypes,courselearningmaterials,curriculuminventoryacademiclevels,curriculuminventoryexports,
    curriculuminventoryinstitutions,curriculuminventorysequenceblocks,
    ilmsessions,programyears,sessions,schools,users
  ilios_api_non_dto_controllers: >-
    (?i)(applicationconfigs|courseclerkshiptypes|courselearningmaterials|curriculuminventoryacademiclevels|curriculuminventoryexports|curriculuminventoryinstitutions|curriculuminventorysequenceblocks|ilmsessions|instructorgroups|objectives|offerings|sessiondescriptions|sessionlearningmaterials)
