parameters:
  ilios_api_valid_endpoints: 'aamcmethods,aamcpcrs,aamcresourcetypes,courses,sessions,users'
  ilios_api_non_dto_controllers: '(?i)(applicationconfigs|ilmsessions|instructorgroups|objectives|offerings|sessiondescriptions|sessionlearningmaterials)'
