ilios_nondto_api_get:
    path:     /{version}/{object}/{id}
    defaults: { _controller: IliosApiBundle:NonDtoApi:get }
    methods:  [GET]
    requirements:
        version: "%ilios_api_valid_api_versions%"
        object: "%ilios_api_non_dto_controllers%"
        id: '(?i)[a-z0-9\-]+'

ilios_nondto_api_put:
    path:     /{version}/{object}/{id}
    defaults: { _controller: IliosApiBundle:NonDtoApi:put }
    methods:  [PUT]
    requirements:
        version: "%ilios_api_valid_api_versions%"
        object: "%ilios_api_non_dto_controllers%"
        id: '(?i)[a-z0-9\-]+'

ilios_nondto_api_getall:
    path:     /{version}/{object}
    defaults: { _controller: IliosApiBundle:NonDtoApi:getAll }
    methods:  [GET]
    requirements:
        version: "%ilios_api_valid_api_versions%"
        object: "%ilios_api_non_dto_controllers%"

ilios_nondto_api_post:
    path:     /{version}/{object}
    defaults: { _controller: IliosApiBundle:NonDtoApi:post }
    methods:  [POST]
    requirements:
        version: "%ilios_api_valid_api_versions%"
        object: "%ilios_api_non_dto_controllers%"

ilios_nondto_api_delete:
    path:     /{version}/{object}/{id}
    defaults: { _controller: IliosApiBundle:NonDtoApi:delete }
    methods:  [DELETE]
    requirements:
        version: "%ilios_api_valid_api_versions%"
        object: "%ilios_api_non_dto_controllers%"
        id: '(?i)[a-z0-9\-]+'