ilios_swagger_file:
    path:     /doc/swagger.yml
    defaults: { _controller: IliosApiBundle:SwaggerDocs:index }
    methods:  [GET]

ilios_nondto_api_get:
    path:     /{version}/{object}/{id}
    defaults: { _controller: IliosApiBundle:NonDtoApi:get }
    methods:  [GET]
    requirements:
        version: 'v\d+'
        object: '(?i)(sessionlearningmaterials|applicationconfigs)'
        id: '(?i)[a-z0-9\-]+'

ilios_api_get:
    path:     /{version}/{object}/{id}
    defaults: { _controller: IliosApiBundle:Api:get }
    methods:  [GET]
    requirements:
        version: 'v\d+'
        object: '(?i)[a-z]+'
        id: '(?i)[a-z0-9\-]+'

ilios_nondto_api_getall:
    path:     /{version}/{object}
    defaults: { _controller: IliosApiBundle:NonDtoApi:getAll }
    methods:  [GET]
    requirements:
        version: 'v\d+'
        object: '(?i)(sessionlearningmaterials|applicationconfigs)'

ilios_api_getall:
    path:     /{version}/{object}
    defaults: { _controller: IliosApiBundle:Api:getAll }
    methods:  [GET]
    requirements:
        version: 'v\d+'
        object: '(?i)[a-z]+'

ilios_api_post:
    path:     /{version}/{object}
    defaults: { _controller: IliosApiBundle:Api:post }
    methods:  [POST]
    requirements:
        version: 'v\d+'
        object: '(?i)[a-z]+'

ilios_api_put:
    path:     /{version}/{object}/{id}
    defaults: { _controller: IliosApiBundle:Api:put }
    methods:  [PUT]
    requirements:
        version: 'v\d+'
        object: '(?i)[a-z]+'
        id: '(?i)[a-z0-9\-]+'

ilios_api_delete:
    path:     /{version}/{object}/{id}
    defaults: { _controller: IliosApiBundle:Api:delete }
    methods:  [DELETE]
    requirements:
        version: 'v\d+'
        object: '(?i)[a-z]+'
        id: '(?i)[a-z0-9\-]+'