services:
    ilios_api.normalizer.entity:
        class: Ilios\ApiBundle\Normalizer\Entity
        calls:
          - [setEntityMetadata, ['@ilioscore.entitymetadata']]
          - [setRegistry, ['@doctrine']]
          - [setPurifier, ['@exercise_html_purifier.default']]

    ilios_api.normalizer.dto:
        class: Ilios\ApiBundle\Normalizer\DTO
        calls:
          - [setEntityMetadata, ['@ilioscore.entitymetadata']]

    ilios_api.valid_object_listener:
            class: Ilios\ApiBundle\EventListener\ValidApiObjectListener
            arguments: ['%ilios_api_valid_endpoints%']
            tags:
                - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }

    ilios_api.endpoint_response_namer:
        class: Ilios\ApiBundle\Service\EndpointResponseNamer
        arguments: ["@kernel"]

    ilios_api.swagger_doc_builder:
        class: Ilios\ApiBundle\Service\SwaggerDocBuilder
        arguments: ["@kernel", "@templating", "@router", "%forceProtocol%"]

    ilios_api.serializer:
      class:     Symfony\Component\Serializer\Serializer
      factory:   ['Ilios\ApiBundle\Service\SerializerFactory', createSerializer]
      arguments: ["@ilios_api.normalizer.entity", "@ilios_api.normalizer.dto"]
