services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Ilios\ApiBundle\:
        resource: '../../*'

    Ilios\ApiBundle\Controller\:
        resource: '../../Controller'
        public: true
        tags: ['controller.service_arguments']

    Ilios\ApiBundle\Controller\SwaggerDocsController:
        public: true
        arguments:
            $kernelRootDir: '%kernel.root_dir%'