ilios_api_getallsessions:
    path:     /{version}/{object}
    defaults: { _controller: IliosApiBundle:Sessions:getAll }
    methods:  [GET]
    requirements:
        version: 'v\d+'
        object: '(?i)sessions'

ilios_api_getallcourses:
    path:     /{version}/{object}
    defaults: { _controller: IliosApiBundle:Courses:getAll }
    methods:  [GET]
    requirements:
        version: 'v\d+'
        object: '(?i)courses'

ilios_api_courserollover:
    path:     /{version}/{object}/{id}/rollover
    defaults: { _controller: IliosApiBundle:Courses:rollover }
    methods:  [POST]
    requirements:
        version: 'v\d+'
        object: '(?i)courses'
        id: '\d+'

ilios_api_getallusers:
    path:     /{version}/{object}
    defaults: { _controller: IliosApiBundle:Users:getAll }
    methods:  [GET]
    requirements:
        version: 'v\d+'
        object: '(?i)users'

ilios_api_authentication_get:
    path:     /{version}/{object}/{userId}
    defaults: { _controller: IliosApiBundle:Authentication:get }
    methods:  [GET]
    requirements:
        version: 'v\d+'
        object: 'authentications'
        userId: '\d+'

ilios_api_authentication_put:
    path:     /{version}/{object}/{userId}
    defaults: { _controller: IliosApiBundle:Authentication:put }
    methods:  [PUT]
    requirements:
        version: 'v\d+'
        object: 'authentications'
        userId: '\d+'

ilios_api_authentication_post:
    path:     /{version}/{object}
    defaults: { _controller: IliosApiBundle:Authentication:post }
    methods:  [POST]
    requirements:
        version: 'v\d+'
        object: 'authentications'

ilios_api_authentication_delete:
    path:     /{version}/{object}/{userId}
    defaults: { _controller: IliosApiBundle:Authentication:delete }
    methods:  [DELETE]
    requirements:
        version: 'v\d+'
        object: 'authentications'
        userId: '\d+'

ilios_api_cohort_put:
    path:     /{version}/{object}/{id}
    defaults: { _controller: IliosApiBundle:Cohort:put }
    methods:  [PUT]
    requirements:
        version: 'v\d+'
        object: 'cohorts'
        id: '\d+'

ilios_api_cohort_post:
    path:     /{version}/{object}
    defaults: { _controller: IliosApiBundle:Cohort:post }
    methods:  [POST]
    requirements:
        version: 'v\d+'
        object: 'cohorts'

ilios_nondto_api_get:
    path:     /{version}/{object}/{id}
    defaults: { _controller: IliosApiBundle:NonDtoApi:get }
    methods:  [GET]
    requirements:
        version: 'v\d+'
        object: "%ilios_api_non_dto_controllers%"
        id: '(?i)[a-z0-9\-]+'

ilios_nondto_api_getall:
    path:     /{version}/{object}
    defaults: { _controller: IliosApiBundle:NonDtoApi:getAll }
    methods:  [GET]
    requirements:
        version: 'v\d+'
        object: "%ilios_api_non_dto_controllers%"