ilios_api_getallsessions:
    path:     /{version}/{object}
    defaults: { _controller: IliosApiBundle:Sessions:getAll }
    methods:  [GET]
    requirements:
        version: 'v\d+'
        object: '(?i)sessions'

ilios_api_getallcourses:
    path:     /{version}/{object}
    defaults: { _controller: IliosApiBundle:Courses:getAll }
    methods:  [GET]
    requirements:
        version: 'v\d+'
        object: '(?i)courses'

ilios_api_courserollover:
    path:     /{version}/{object}/{id}/rollover
    defaults: { _controller: IliosApiBundle:Courses:rollover }
    methods:  [POST]
    requirements:
        version: 'v\d+'
        object: '(?i)courses'
        id: '\d+'

ilios_nondto_api_get:
    path:     /{version}/{object}/{id}
    defaults: { _controller: IliosApiBundle:NonDtoApi:get }
    methods:  [GET]
    requirements:
        version: 'v\d+'
        object: "%ilios_api_non_dto_controllers%"
        id: '(?i)[a-z0-9\-]+'

ilios_nondto_api_getall:
    path:     /{version}/{object}
    defaults: { _controller: IliosApiBundle:NonDtoApi:getAll }
    methods:  [GET]
    requirements:
        version: 'v\d+'
        object: "%ilios_api_non_dto_controllers%"