parameters:
    ilioscore.dataloader.aamcmethod.class: IliosCoreBundleTestsDataLoader\AamcMethodData
    ilioscore.dataloader.aamcpcrs.class: IliosCoreBundleTestsDataLoader\AamcPcrsData
    ilioscore.dataloader.alertchangetype.class: IliosCoreBundleTestsDataLoader\AlertChangeTypeData
    ilioscore.dataloader.alert.class: IliosCoreBundleTestsDataLoader\AlertData
    ilioscore.dataloader.assessmentoption.class: IliosCoreBundleTestsDataLoader\AssessmentOptionData
    ilioscore.dataloader.cohort.class: IliosCoreBundleTestsDataLoader\CohortData
    ilioscore.dataloader.competency.class: IliosCoreBundleTestsDataLoader\CompetencyData
    ilioscore.dataloader.courselearningmaterial.class: IliosCoreBundleTestsDataLoader\CourseLearningMaterialData
    ilioscore.dataloader.course.class: IliosCoreBundleTestsDataLoader\CourseData
    ilioscore.dataloader.courseclerkshiptype.class: IliosCoreBundleTestsDataLoader\CourseClerkshipTypeData
    ilioscore.dataloader.curriculuminventoryacademiclevel.class: IliosCoreBundleTestsDataLoader\CurriculumInventoryAcademicLevelData
    ilioscore.dataloader.curriculuminventoryexport.class: IliosCoreBundleTestsDataLoader\CurriculumInventoryExportData
    ilioscore.dataloader.curriculuminventoryinstitution.class: IliosCoreBundleTestsDataLoader\CurriculumInventoryInstitutionData
    ilioscore.dataloader.curriculuminventoryreport.class: IliosCoreBundleTestsDataLoader\CurriculumInventoryReportData
    ilioscore.dataloader.curriculuminventorysequenceblock.class: IliosCoreBundleTestsDataLoader\CurriculumInventorySequenceBlockData
    ilioscore.dataloader.curriculuminventorysequenceblocksession.class: IliosCoreBundleTestsDataLoader\CurriculumInventorySequenceBlockSessionData
    ilioscore.dataloader.curriculuminventorysequence.class: IliosCoreBundleTestsDataLoader\CurriculumInventorySequenceData
    ilioscore.dataloader.department.class: IliosCoreBundleTestsDataLoader\DepartmentData
    ilioscore.dataloader.discipline.class: IliosCoreBundleTestsDataLoader\DisciplineData
    ilioscore.dataloader.ilmsessionfacet.class: NOT_FOUND
    ilioscore.dataloader.ingestionexception.class: IliosCoreBundleTestsDataLoader\IngestionExceptionData
    ilioscore.dataloader.instructorgroup.class: IliosCoreBundleTestsDataLoader\InstructorGroupData
    ilioscore.dataloader.learnergroup.class: IliosCoreBundleTestsDataLoader\LearnerGroupData
    ilioscore.dataloader.learningmaterialstatus.class: IliosCoreBundleTestsDataLoader\LearningMaterialStatusData
    ilioscore.dataloader.learningmaterialuserrole.class: IliosCoreBundleTestsDataLoader\LearningMaterialUserRoleData
    ilioscore.dataloader.learningmaterial.class: IliosCoreBundleTestsDataLoader\CourseLearningMaterialData
    ilioscore.dataloader.objective.class: IliosCoreBundleTestsDataLoader\ObjectiveData
    ilioscore.dataloader.offering.class: IliosCoreBundleTestsDataLoader\OfferingData
    ilioscore.dataloader.programyear.class: IliosCoreBundleTestsDataLoader\ProgramYearData
    ilioscore.dataloader.programyearsteward.class: IliosCoreBundleTestsDataLoader\ProgramYearStewardData
    ilioscore.dataloader.program.class: IliosCoreBundleTestsDataLoader\ProgramData
    ilioscore.dataloader.publishevent.class: IliosCoreBundleTestsDataLoader\PublishEventData
    ilioscore.dataloader.recurringevent.class: IliosCoreBundleTestsDataLoader\RecurringEventData
    ilioscore.dataloader.report.class: IliosCoreBundleTestsDataLoader\CurriculumInventoryReportData
    ilioscore.dataloader.school.class: IliosCoreBundleTestsDataLoader\SchoolData
    ilioscore.dataloader.sessiondescription.class: IliosCoreBundleTestsDataLoader\SessionDescriptionData
    ilioscore.dataloader.sessionlearningmaterial.class: IliosCoreBundleTestsDataLoader\SessionLearningMaterialData
    ilioscore.dataloader.sessiontype.class: IliosCoreBundleTestsDataLoader\SessionTypeData
    ilioscore.dataloader.session.class: IliosCoreBundleTestsDataLoader\CurriculumInventorySequenceBlockSessionData
    ilioscore.dataloader.usermadereminder.class: IliosCoreBundleTestsDataLoader\UserMadeReminderData
    ilioscore.dataloader.userrole.class: IliosCoreBundleTestsDataLoader\LearningMaterialUserRoleData
    ilioscore.dataloader.user.class: IliosCoreBundleTestsDataLoader\UserData
    ilioscore.dataloader.reportpovalue.class: IliosCoreBundleTestsDataLoader\ReportPoValueData

services:
    ilioscore.dataloader.aamcmethod:
        class: %ilioscore.dataloader.aamcmethod.class%
    ilioscore.dataloader.aamcpcrs:
        class: %ilioscore.dataloader.aamcpcrs.class%
    ilioscore.dataloader.alertchangetype:
        class: %ilioscore.dataloader.alertchangetype.class%
    ilioscore.dataloader.alert:
        class: %ilioscore.dataloader.alert.class%
    ilioscore.dataloader.assessmentoption:
        class: %ilioscore.dataloader.assessmentoption.class%
    ilioscore.dataloader.cohort:
        class: %ilioscore.dataloader.cohort.class%
    ilioscore.dataloader.competency:
        class: %ilioscore.dataloader.competency.class%
    ilioscore.dataloader.courselearningmaterial:
        class: %ilioscore.dataloader.courselearningmaterial.class%
    ilioscore.dataloader.course:
        class: %ilioscore.dataloader.course.class%
    ilioscore.dataloader.courseclerkshiptype:
        class: %ilioscore.dataloader.courseclerkshiptype.class%
    ilioscore.dataloader.curriculuminventoryacademiclevel:
        class: %ilioscore.dataloader.curriculuminventoryacademiclevel.class%
    ilioscore.dataloader.curriculuminventoryexport:
        class: %ilioscore.dataloader.curriculuminventoryexport.class%
    ilioscore.dataloader.curriculuminventoryinstitution:
        class: %ilioscore.dataloader.curriculuminventoryinstitution.class%
    ilioscore.dataloader.curriculuminventoryreport:
        class: %ilioscore.dataloader.curriculuminventoryreport.class%
    ilioscore.dataloader.curriculuminventorysequenceblock:
        class: %ilioscore.dataloader.curriculuminventorysequenceblock.class%
    ilioscore.dataloader.curriculuminventorysequenceblocksession:
        class: %ilioscore.dataloader.curriculuminventorysequenceblocksession.class%
    ilioscore.dataloader.curriculuminventorysequence:
        class: %ilioscore.dataloader.curriculuminventorysequence.class%
    ilioscore.dataloader.department:
        class: %ilioscore.dataloader.department.class%
    ilioscore.dataloader.discipline:
        class: %ilioscore.dataloader.discipline.class%
    ilioscore.dataloader.ilmsessionfacet:
        class: %ilioscore.dataloader.ilmsessionfacet.class%
    ilioscore.dataloader.ingestionexception:
        class: %ilioscore.dataloader.ingestionexception.class%
    ilioscore.dataloader.instructorgroup:
        class: %ilioscore.dataloader.instructorgroup.class%
    ilioscore.dataloader.learnergroup:
        class: %ilioscore.dataloader.learnergroup.class%
    ilioscore.dataloader.learningmaterialstatus:
        class: %ilioscore.dataloader.learningmaterialstatus.class%
    ilioscore.dataloader.learningmaterialuserrole:
        class: %ilioscore.dataloader.learningmaterialuserrole.class%
    ilioscore.dataloader.learningmaterial:
        class: %ilioscore.dataloader.learningmaterial.class%
    ilioscore.dataloader.objective:
        class: %ilioscore.dataloader.objective.class%
    ilioscore.dataloader.offering:
        class: %ilioscore.dataloader.offering.class%
    ilioscore.dataloader.programyear:
        class: %ilioscore.dataloader.programyear.class%
    ilioscore.dataloader.programyearsteward:
        class: %ilioscore.dataloader.programyearsteward.class%
    ilioscore.dataloader.program:
        class: %ilioscore.dataloader.program.class%
    ilioscore.dataloader.publishevent:
        class: %ilioscore.dataloader.publishevent.class%
    ilioscore.dataloader.recurringevent:
        class: %ilioscore.dataloader.recurringevent.class%
    ilioscore.dataloader.report:
        class: %ilioscore.dataloader.report.class%
    ilioscore.dataloader.school:
        class: %ilioscore.dataloader.school.class%
    ilioscore.dataloader.sessiondescription:
        class: %ilioscore.dataloader.sessiondescription.class%
    ilioscore.dataloader.sessionlearningmaterial:
        class: %ilioscore.dataloader.sessionlearningmaterial.class%
    ilioscore.dataloader.sessiontype:
        class: %ilioscore.dataloader.sessiontype.class%
    ilioscore.dataloader.session:
        class: %ilioscore.dataloader.session.class%
    ilioscore.dataloader.usermadereminder:
        class: %ilioscore.dataloader.usermadereminder.class%
    ilioscore.dataloader.userrole:
        class: %ilioscore.dataloader.userrole.class%
    ilioscore.dataloader.user:
        class: %ilioscore.dataloader.user.class%
    ilioscore.dataloader.reportpovalue:
        class: %ilioscore.dataloader.reportpovalue.class%
