services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Ilios\CoreBundle\Entity\Manager\MeshQualifierManager:
        class: Ilios\CoreBundle\Entity\Manager\BaseManager
        arguments:
            $class: 'Ilios\CoreBundle\Entity\MeshQualifier'
    Ilios\CoreBundle\Entity\Manager\MeshSemanticTypeManager:
        class: Ilios\CoreBundle\Entity\Manager\BaseManager
        arguments:
            $class: 'Ilios\CoreBundle\Entity\MeshSemanticType'
    Ilios\CoreBundle\Entity\Manager\MeshTreeManager:
        class: Ilios\CoreBundle\Entity\Manager\BaseManager
        arguments:
            $class: 'Ilios\CoreBundle\Entity\MeshTree'
    Ilios\CoreBundle\Entity\Manager\PermissionManager:
        class: Ilios\CoreBundle\Entity\Manager\BaseManager
        arguments:
            $class: 'Ilios\CoreBundle\Entity\Permission'
    Ilios\CoreBundle\Entity\Manager\ReportManager:
        class: Ilios\CoreBundle\Entity\Manager\BaseManager
        arguments:
            $class: 'Ilios\CoreBundle\Entity\Report'
    Ilios\CoreBundle\Entity\Manager\SchoolConfigManager:
        class: Ilios\CoreBundle\Entity\Manager\BaseManager
        arguments:
            $class: 'Ilios\CoreBundle\Entity\SchoolConfig'
    Ilios\CoreBundle\Entity\Manager\UserMadeReminderManager:
        class: Ilios\CoreBundle\Entity\Manager\BaseManager
        arguments:
            $class: 'Ilios\CoreBundle\Entity\UserMadeReminder'
    Ilios\CoreBundle\Entity\Manager\UserRoleManager:
        class: Ilios\CoreBundle\Entity\Manager\BaseManager
        arguments:
            $class: 'Ilios\CoreBundle\Entity\UserRole'
    Ilios\CoreBundle\Entity\Manager\VocabularyManager:
        class: Ilios\CoreBundle\Entity\Manager\BaseManager
        arguments:
            $class: 'Ilios\CoreBundle\Entity\Vocabulary'