services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Ilios\CoreBundle\Entity\Manager\VocabularyManager:
        class: Ilios\CoreBundle\Entity\Manager\BaseManager
        arguments:
            $class: 'Ilios\CoreBundle\Entity\Vocabulary'