services:
    filesystem:
        class: Symfony\Component\Filesystem\Filesystem
    ilioscore.listener.timestamp:
        class: Ilios\CoreBundle\EventListener\TimestampListener
        tags:
            - { name: doctrine.event_listener, event: onFlush }
    ilioscore.listener.updatesession:
        class: Ilios\CoreBundle\EventListener\UpdateSessionTimestamp
        tags:
            - { name: doctrine.event_listener, event: onFlush }
    ilioscore.listener.updateoffering:
        class: Ilios\CoreBundle\EventListener\UpdateOfferingTimestamp
        tags:
            - { name: doctrine.event_listener, event: onFlush }
    ilioscore.listener.logentitychanges:
        class: Ilios\CoreBundle\EventListener\LogEntityChanges
        arguments: ['@ilioscore.logger']
        tags:
            - { name: doctrine.event_listener, event: onFlush } 
        calls:
        - [ setContainer, ["@service_container"] ]
    ilioscore.temporary_filesystem:
            class: Ilios\CoreBundle\Classes\TemporaryFileSystem
            arguments: ['@filesystem', "%kernel.root_dir%"]
    ilioscore.filesystem:
            class: Ilios\CoreBundle\Classes\IliosFileSystem
            arguments: ['@filesystem', "%ilios_core.file_store_path%"]
    ilioscore.logger:
        class: Ilios\CoreBundle\Service\Logger
        arguments: ['@security.token_storage', '@ilioscore.auditlog.manager']
