services:
    ilioscore.listener.timestamp:
        class: Ilios\CoreBundle\EventListener\TimestampListener
        tags:
            - { name: doctrine.event_listener, event: onFlush }
    ilioscore.listener.updatesession:
        class: Ilios\CoreBundle\EventListener\UpdateSessionTimestamp
        tags:
            - { name: doctrine.event_listener, event: onFlush }
