services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Ilios\CoreBundle\:
        resource: '../../*'
        exclude: '../../{Entity,Controller}'

    Ilios\CoreBundle\Controller\:
        resource: '../../Controller'
        public: true
        tags: ['controller.service_arguments']

    Ilios\CoreBundle\Controller\ExceptionController:
        public: true
        arguments:
            $environment: '%kernel.environment%'

    Alchemy\Zippy\Zippy:
        factory: ['Alchemy\Zippy\Zippy', 'load']

