name: Future PHP Versions

on:
  schedule:
    - cron: '33 1 * * 1' # weekly, on Monday morning

env:
  MAILER_DSN: null://null
  ILIOS_LOCALE: en
  ILIOS_SECRET: ThisTokenIsNotSoSecretChangeIt
  ILIOS_FILE_SYSTEM_STORAGE_PATH: /tmp
  SYMFONY_DEPRECATIONS_HELPER: disabled=1
  future_php: 8.2

jobs:
  test:
    name: Test PHP v${{ env.latest_php }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use PHP ${{ env.latest_php }}
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ env.latest_php }}
        coverage: none
        tools: pecl
        extensions: apcu
    - name: install dependencies
      run: composer install --no-interaction --prefer-dist
    - name: Run Tests
      run: vendor/bin/phpunit
